### PR TITLE
Create .DS_Store

### PR DESCRIPTION
**Pull request by DanLS777**

### CODE REVIEW

**Review by DanLS777 — COMMENTED** [review]
Please help me

**Comment by bigcat88** [comment]
> Please help me

Can you please clarify, with what we can help you?

**Comment by DanLS777** [comment]
Hello,

I didn’t expect you to actually try and help me, VS is unable to read or
access the .DS_Store files on my Mac and won’t execute webui.sh so it
suggested I setup a fork which I had to request through you guys. But even
with access it still won’t work so I am probably going to have to start
again without ComfyUI unfortunately.

Thanks for reaching out

**Comment by shawnington** [comment]
Very confused, is there a problem with the .DS_store file or accessing it?

For non mac people, the .DS_store files basically stores metadata about a folder. like icon positions for different view options. Not sure how it would be relevant to comfy, unless it's somehow messing with the ability to load files via a modal window.

**Pull request closed without merging**
