### PR TITLE
Add audio widget

### PR DESCRIPTION
**Pull request by huchenlei**
This PR adds audio widget for `SaveAudio` node and `LoadAudio` node.

image

Reference PR on image upload widget impl: https://github.com/comfyanonymous/ComfyUI/pull/55

Synced with TS repo PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/54

Stable Audio Guide: https://gist.github.com/comfyanonymous/0e04181f7fd01301230adc106b691cc2

### CODE REVIEW

**Comment by huchenlei** [comment]
Browser test is fixed by https://github.com/comfyanonymous/ComfyUI/pull/3865.

**Comment by comfyanonymous** [comment]
I think it's best if the widget doesn't appear if there's no audio in the SaveAudio node:
image

There's a bug with the LoadAudio widget:

1. Put a test.flac file in the comfyui/input folder

2. Select it in the LoadAudio widget

It can't be played:
image

It's because url it's trying to get is wrong:
image

**Comment by huchenlei** [comment]
> I think it's best if the widget doesn't appear if there's no audio in the SaveAudio node: image
> 
> There's a bug with the LoadAudio widget:
> 
> 1. Put a test.flac file in the comfyui/input folder
> 2. Select it in the LoadAudio widget
> 
> It can't be played: image
> 
> It's because url it's trying to get is wrong: image

1. `SaveAudio` node now hides the widget initially
2. `LoadAudio` node now automatically init the audio play widget with the default selected audio file

**Comment by comfyanonymous** [comment]
I still see the audio widget initially on the SaveAudio node.

When loading an audio workflow from the history the audio widget in the SaveAudio node does not work.

**Comment by huchenlei** [comment]
> I still see the audio widget initially on the SaveAudio node.
> 
> When loading an audio workflow from the history the audio widget in the SaveAudio node does not work.

1. CSS fixed. (Previously not synced with TS impl)
2. Logic added to populate audio widget when loading workflow from history

**Comment by huchenlei** [comment]
https://github.com/comfyanonymous/ComfyUI/assets/20929282/65542d4d-fdf8-456f-9b1a-f86b84e33a62

**Comment by jn-jairo** [comment]
Great, so now I can port my python scripts for audio to ComfyUI, thank you.

**Comment by 3blackbar** [comment]
OK heres a fix , i have no time for pull request tho atm     

    def save_audio(self, audio, filename_prefix="ComfyUI", prompt=None, extra_pnginfo=None):
        filename_prefix += self.prefix_append
        full_output_folder, filename, counter, subfolder, filename_prefix = folder_paths.get_save_image_path(filename_prefix, self.output_dir)
        results = []

        metadata = {}
        if not args.disable_metadata:
            if prompt is not None:
                metadata["prompt"] = json.dumps(prompt)
            if extra_pnginfo is not None:
                for x in extra_pnginfo:
                    metadata[x] = json.dumps(extra_pnginfo[x])

        for (batch_number, waveform) in enumerate(audio["waveform"]):
            filename_with_batch_num = filename.replace("%batch_num%", str(batch_number))
            file = f"{filename_with_batch_num}_{counter:05}_.flac"

            # Ensure waveform is a 2D tensor
            waveform = waveform.squeeze()  # Remove single-dimensional entries

            if waveform.ndim == 1:
                waveform = waveform.unsqueeze(0)  # Convert 1D tensor to 2D if needed

            buff = io.BytesIO()
            waveform = waveform.cpu()
            torchaudio.save(buff, waveform, audio["sample_rate"], format="FLAC")

            buff = insert_or_replace_vorbis_comment(buff, metadata)

            with open(os.path.join(full_output_folder, file), 'wb') as f:
                f.write(buff.getbuffer())

            results.append({
                "filename": file,
                "subfolder": subfolder,
                "type": self.type
            })
            counter += 1

        return { "ui": { "audio": results } }

**Pull request merged**
