### PR TITLE
Init docker support (Nvidia and AMD)

### PR DESCRIPTION
**Pull request by LEv145**
Minimum initial docker-compose to run
изображение

https://github.com/comfyanonymous/ComfyUI/issues/188

How to use:
```
docker compose --profile cpu up  # CPU
docker compose --profile nvidia up  # Nvidia with https://download.pytorch.org/whl/cu117 
docker compose --profile amd up  # AMD with https://download.pytorch.org/whl/rocm5.4.2
docker compose --profile amd6600 up  # like amd profile, but with HSA_OVERRIDE_GFX_VERSION=10.3.0
```

### CODE REVIEW

**Comment by paulo-coronado** [comment]
Hey @LEv145! Thanks for sharing it! I am also working with Comfy + Docker hosted on Runpod's Serverless GPU, but I am getting NVIDIA erros. I can't link my GPU with the containers... 😢

**Comment by LEv145** [comment]
> Hey @LEv145! Thanks for sharing it! I am also working with Comfy + Docker hosted on Runpod's Serverless GPU, but I am getting NVIDIA erros. I can't link my GPU with the containers... cry

I'm happy to share
On my graphics card, docker-compose works stably without errors

Probably a problem in `nvidia-docker`, I hope you fix it

**Comment by comfyanonymous** [comment]
Unfortunately I don't have a nvidia card so I can't test this.

**Comment by LEv145** [comment]
> Unfortunately I don't have a nvidia card so I can't test this.

I have nvidia 2600 super working on my card, it should work on any card from nvidia, because I use `nvidia-docker`

I can add a version without gpu to docker

**Comment by LEv145** [comment]
I'm not at home, I did it before I tested it:
https://github.com/LEv145/ComfyUI/tree/cpu-docker

Run with cpu:
```
docker compose --profile cpu up
```
Run with nvidia gpu:
```
docker compose --profile nvidia up
```

**Comment by LEv145** [comment]
@comfyanonymous Try amd gpu
It's using https://download.pytorch.org/whl/cu117 xformers not https://download.pytorch.org/whl/rocm5.4.2

**Comment by paulo-coronado** [comment]
Hello, @LEv145! Thanks for adding Docker support! Could you please add me on Discord @pcoronado#4338? I new to docker compose and I have some questions about your fork :)

**Comment by LEv145** [comment]
Let's go
https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/384

**Comment by kwaa** [comment]
If merged, I would be interested in adding Intel Arc Graphics support.

**Comment by LEv145** [comment]
Good stuff:
https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/384

**Comment by kwaa** [comment]
> Good stuff: [AbdBarho/stable-diffusion-webui-docker#384](https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/384)

Unfortunately, this repo only seems to support NVIDIA graphics cards.

**Comment by LEv145** [comment]
Good stuff:
https://github.com/YanWenKun/ComfyUI-Docker

**Pull request closed without merging**
