### PR TITLE
ComfyUI - Comfy Menu

### PR DESCRIPTION
**Pull request by WASasquatch**
A comfy menu for ComfyUI

Screenshot_36
Screenshot_37
Screenshot_38
Screenshot_39

### CODE REVIEW

**Comment by comfyanonymous** [comment]
I don't like how the buttons "see queue" and "see history" move away from the mouse when clicked, can you fix that?

**Comment by WASasquatch** [comment]
> I don't like how the buttons "see queue" and "see history" move away from the mouse when clicked, can you fix that?

Can you demonstrate? The buttons are fixed for me on hover and event.

**Comment by comfyanonymous** [comment]
I tried your branch as is in chromium and firefox and when I press the "see queue" button the close button is not directly under my mouse.

**Comment by WASasquatch** [comment]
> I tried your branch as is in chromium and firefox and when I press the "see queue" button the close button is not directly under my mouse.

That's the translation to center of the screen, so if you open it, it doesn't open off screen depending on your browser.

**Comment by comfyanonymous** [comment]
Lets wait for this: #276 to be merged then. It has a similar issue and the fix for it might fix the issue with yours.

**Comment by WASasquatch** [comment]
> Lets wait for this: #276 to be merged then. It has a similar issue and the fix for it might fix the issue with yours.

Yeah, and I am redoing the whole thing too. The elements all should have classes for styles anyway so went and got those in. Also making it a little more compact for the height deal with other resolutions

**Comment by WASasquatch** [comment]
@comfyanonymous how does this revamp look? It's much more compact, and uses internal node network color themes for buttons

Screenshot_45
Screenshot_47
Screenshot_46

**Pull request closed without merging**
