### PR TITLE
improve: Mask Editor

### PR DESCRIPTION
**Pull request by ltdrdata**
improved:
1. Basic structure improvement
2. Enhance to display the image in the center of the dialog.
3. Zoom feature: ctrl + wheel
4. Pan feature: ctrl + left button drag

fixed:
Fix the issue where the existing mask does not appear when loading an image with a mask.

### CODE REVIEW

**Comment by ltdrdata** [comment]
> fixed: Fix the issue where the existing mask does not appear when loading an image with a mask.
> 
> Is not fixed for me!! the second time that I open the mask editor, the mask disappear!
> 
>  mask.mp4

What is your browser?

**Comment by ShmuelRonen** [comment]
> > fixed: Fix the issue where the existing mask does not appear when loading an image with a mask.
> > Is not fixed for me!! the second time that I open the mask editor, the mask disappear!
> > mask.mp4
> 
> What is your browser?
> 
> Do the zoom and pan functions work with ctrl-wheel and ctrl-drag, properly?

1. I use the Brave browser for a long time (chrom angien). 
2. The zoom function with Crtl and mouse weel works 4 me. but strangely it impact the main screen to enlarge or reduce simultainly...

**Comment by ltdrdata** [comment]
> > > fixed: Fix the issue where the existing mask does not appear when loading an image with a mask.
> > > Is not fixed for me!! the second time that I open the mask editor, the mask disappear!
> > > mask.mp4
> > 
> > 
> > What is your browser?
> > Do the zoom and pan functions work with ctrl-wheel and ctrl-drag, properly?
> 
> 1. I use the Brave browser for a long time (chrome engine).
> 2. The zoom function with Crtl and mouse weel works 4 me. but strangely it impact the main screen to enlarge or reduce simultainly...

Unfortunately, Browser is not the problem. I have no issue on Brave browser.
There is a possibility of custom nodes problem.

In my experience, using front-end extensions that manipulate styles, such as `ricing`, has led to layout issues.

Try testing it once by disabling all `custom_nodes` and removing all extensions from` web/extensions`, except the `web/extensions/core`.

**Comment by ShmuelRonen** [comment]
> > > > fixed: Fix the issue where the existing mask does not appear when loading an image with a mask.
> > > > Is not fixed for me!! the second time that I open the mask editor, the mask disappear!
> > > > mask.mp4
> > > 
> > > 
> > > What is your browser?
> > > Do the zoom and pan functions work with ctrl-wheel and ctrl-drag, properly?
> > 
> > 
> > 
> > 1. I use the Brave browser for a long time (chrome engine).
> > 2. The zoom function with Crtl and mouse weel works 4 me. but strangely it impact the main screen to enlarge or reduce simultainly...
> 
> Unfortunately, Browser is not the problem. I have no issue on Brave browser. There is a possibility of custom nodes problem.
> 
> In my experience, using front-end extensions that manipulate styles, such as `ricing`, has led to layout issues.
> 
> Try testing it once by disabling all `custom_nodes` and removing all extensions from` web/extensions`, except the `web/extensions/core`.

I made another test that show that after screen refresh, the mask come back. but not a practical solution...

https://github.com/comfyanonymous/ComfyUI/assets/80190186/f5f4562c-a79f-44b9-8215-bd7a5c53ab42

**Comment by ltdrdata** [comment]
> > > > > fixed: Fix the issue where the existing mask does not appear when loading an image with a mask.
> > > > > Is not fixed for me!! the second time that I open the mask editor, the mask disappear!
> > > > > mask.mp4
> > > > 
> > > > 
> > > > What is your browser?
> > > > Do the zoom and pan functions work with ctrl-wheel and ctrl-drag, properly?
> > > 
> > > 
> > > 
> > > 1. I use the Brave browser for a long time (chrome engine).
> > > 2. The zoom function with Crtl and mouse weel works 4 me. but strangely it impact the main screen to enlarge or reduce simultainly...
> > 
> > 
> > Unfortunately, Browser is not the problem. I have no issue on Brave browser. There is a possibility of custom nodes problem.
> > In my experience, using front-end extensions that manipulate styles, such as `ricing`, has led to layout issues.
> > Try testing it once by disabling all `custom_nodes` and removing all extensions from` web/extensions`, except the `web/extensions/core`.
> 
> I made another test that show that after screen refresh, the mask come back. but not a practical solution...
> 
>  redray.mp4

Your mask editor appears to be an older version that has not incorporated the PR. The current PR has been merged to the latest version of ComfyUI, so update ComfyUI and check it again.

**Comment by ShmuelRonen** [comment]
Thanks! it works for me. Perfect!!!

**Comment by ShmuelRonen** [comment]
Another thing. When I zoom in a image, I can't move it up or down Like in photoshop but stuck in the middle of the frame. there is a solution?

**Pull request merged**
