### PR TITLE
add avif parsing function

### PR DESCRIPTION
**Pull request by audioscavenger**
add avif parsing function. added as much comments as I could. more details [here](https://www.it-cooking.com/how-to-read-exif-hexadecimal-metadata-from-avif-with-javascript/)

### CODE REVIEW

**Comment by comfyanonymous** [comment]
do you have a test file for this or a way to create one?

**Comment by audioscavenger** [comment]
You are right, sorry I should have included a test rig.
* Attached is a basic json and output files, and also the *-2AVIF *-2WEBP files converted from png with imagick + exiftool. 
* I have made the getAvifMetadata and getWebpMetadata more resilient to errors by adding a simple test if the `data[key]` is undifined.
* I have left the comments and removed all the debug console.log
[AVIF-validation.zip](https://github.com/comfyanonymous/ComfyUI/files/15457545/AVIF-validation.zip)
If you don't want the outputs, here is just the json for testing:
[AVIF-validation.json](https://github.com/comfyanonymous/ComfyUI/files/15457580/AVIF-validation.json)

I have also completely updated the post that explains all this at [avif parsing explanations](https://www.it-cooking.com/how-to-read-exif-hexadecimal-metadata-from-avif-with-javascript/)

All seems to work perfectly, i tested different workflows with various prompt sises, and converted lots of png to avif and webp, all load perfectly!

**Comment by audioscavenger** [comment]
hi, I see that the number of PR is piling up... sorry that I cannot help you more. Is there anyone that can back you up for testing PR's? 
I still use this code myself and haven't found a bug since I submitted the last update.
Please let me know if you need more details on how it reads the AVIF. I basically implemented what you did with Webp, but with different chunk sizes and dynamic position detections, based off a meticulous ascii analysis of different AVIF files + the RFC I could find.

**Comment by mcmonkey4eva** [comment]
We're gonna be working to improve PR handling here very soon

**Comment by mcmonkey4eva** [comment]
Could you please rebuild the PR? It has a merge conflict caused by the recent addition of audio file support.

**Comment by mcmonkey4eva** [comment]
frontend is replaced by https://github.com/Comfy-Org/ComfyUI_frontend now

**Pull request closed without merging**
