### PR TITLE
Fix preview latent on AMD Devices for Windows.

### PR DESCRIPTION
**Pull request by traugdor**
Improve Latent Preview by forcing `dtype=uint8`
Check if device supports non-blocking

### CODE REVIEW

**Comment by traugdor** [comment]
Closes #3539

**Comment by dnswd** [comment]
Does the uint8 casting still needed after changes on `device_supports_non_blocking`?

**Comment by traugdor** [comment]
> Does the uint8 casting still needed after changes on `device_supports_non_blocking`?

It seems so. I was still running into issues without it, but if you can provide evidence that it's not needed on some AMD devices, then it may be worth revisiting in the future.

**Comment by traugdor** [comment]
Closing in favor of commits to main repo that have addressed this issue.

**Comment by traugdor** [comment]
I am reopening this pull request because after updating ComfyUI, I am still getting this error in the `latent_preview.py` file:

```
TypeError: Cannot handle this data type: (1, 1, 3), <f4
```

**Comment by mcmonkey4eva** [comment]
If this remains an issue, please repush the change to resolve the merge conflict

**Comment by traugdor** [comment]
This issue is addressed in #6300 

Please ensure that PR is merged.

**Pull request closed without merging**
