### PR TITLE
Allow connect primitive nodes to route nodes  

### PR DESCRIPTION
**Pull request by omar92**
Allow connecting primitive nodes to the route nodes that have value 

This is built on top of this pull request  
https://github.com/comfyanonymous/ComfyUI/pull/452

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Some small issues. It doesn't work with sampler_name in KSampler for example and the reroute node also doesn't behave very well when connected to sampler_name.

**Comment by Bocian-1** [comment]
> Some small issues. It doesn't work with sampler_name in KSampler for example and the reroute node also doesn't behave very well when connected to sampler_name.

I've had problems with connecting primitive nodes to some KSampler inputs already so it could be that
see #461

**Comment by omar92** [comment]
seems like an old bug -- not related to this push , but will try fix it

**Comment by pythongosssss** [comment]
Doesn't seem to be working for me, not sure if some other change has broken it since you implemented it (as I think it was working previously when I tried)?

Load default
Convert EmptyLatentImage width to input
Connect reroute to width input
Connect primitive to reroute


Each time I change the value on the primitive (or try and queue prompt):
```
Uncaught TypeError: input.widget is undefined
    applyToGraph  extensions/core/widgetInputs.js:206
    callback  extensions/core/widgetInputs.js:324
    inner_value_change  lib/litegraph.core.js:10068
    processNodeWidgets  lib/litegraph.core.js:10018
    setTimeout handler*LGraphCanvas.prototype.processNodeWidgets  lib/litegraph.core.js:10016
    processMouseMove  lib/litegraph.core.js:6276
    processMouseMove  scripts/app.js:460
    pointerListenerAdd  lib/litegraph.core.js:14088
    processMouseDown  lib/litegraph.core.js:5774
    processMouseDown  scripts/app.js:434
    pointerListenerAdd  lib/litegraph.core.js:14088
    bindEvents  lib/litegraph.core.js:5542
    setCanvas  lib/litegraph.core.js:5501
    LGraphCanvas  lib/litegraph.core.js:5257
    setup  scripts/app.js:722
    async*  :12
12 widgetInputs.js:206:25
```

**Comment by mcmonkey4eva** [comment]
Gonna close this for now as it was reported not working a few months back without update. Can reopen if you get back at it.

**Pull request closed without merging**
