### PR TITLE
Add MaHiRo (improved/alternate CFG)

### PR DESCRIPTION
**Pull request by yoinked-h**
long explanation of what it is is [here](https://huggingface.co/spaces/yoinked/blue-arxiv) (2024-1208.1) 

note: if the node name has encoding issues (utf 8/whatever), id suggest to replace the face at the end with `(>w<)`

### CODE REVIEW

**Comment by comfyanonymous** [comment]
You need to add the nodes_mahiro.py here: https://github.com/comfyanonymous/ComfyUI/blob/master/nodes.py#L2151

**Comment by asagi4** [comment]
Since this still uses the regular CFG output, couldn't you implement this as a post-cfg function instead so that it can be combined with other CFG methods?

**Comment by yoinked-h** [comment]
> You need to add the nodes_mahiro.py here: https://github.com/comfyanonymous/ComfyUI/blob/master/nodes.py#L2151

Added, thanks for mentioning!

> Since this still uses the regular CFG output, couldn't you implement this as a post-cfg function instead so that it can be combined with other CFG methods?

I've made the function work as a post-cfg function now, though I feel like it should work as a replacement for CFG, please tell me if the function broke while it was being converted though

**Comment by catboxanon** [comment]
It doesn't work as post-cfg because `cond_scale` is not passed into `args`, so now it throws a `KeyError`.

**Comment by yoinked-h** [comment]
if this gets approved then i think i can just revert the commit, ty @catboxanon

**Comment by yoinked-h** [comment]
i manually implement cfg as it is part of the way mahiro works (make guess, compare to CFG to see if its good or not, correct), though i think it should be replaced, since right now it'd override whatever cfg function came before

**Pull request merged**
