### PR TITLE
Adds dither, sharpen, blur, canny, color correct and kmeans quantize nodes

### PR DESCRIPTION
**Pull request by EllangoK**
Adds `Dither`, `Sharpen`, `GaussianBlur`, `CannyEdgeDetection`, `ColorCorrect`, `KMeansQuantize` Nodes.

I believe most of these are very common uses cases, and are demonstrated below.

image

Ignore pixel sort as while it is shown it iss not added as it is complex and definitely not going to be used by everybody. It can be found [here](https://github.com/EllangoK/ComfyUI-post-processing-nodes) though for anyone interested.

`numpy`, `cv2`, and `PIL` are all already used in various parts of the project, so new dependencies.

### CODE REVIEW

**Comment by comfyanonymous** [comment]
opencv isn't currently a required dependency but maybe I should make it one.

**Comment by EllangoK** [comment]
Is it not, for example if you just search cv2 https://github.com/comfyanonymous/ComfyUI/blob/9a27030519c6e1e2024df50cdc547f6a05d714bc/comfy/ldm/modules/midas/api.py#L3 one of many results is that?

**Comment by EllangoK** [comment]
I added one more node, this is actually imo the most important node as it is the blend node, and lets you blend between two images. 

If you think this is too many nodes (imo I would keep all as they are all basic operations), but if you had to keep only two I would just keep the ColorCorrect node and Blend Node. I still would suggest keeping all of them, as otherwise everyone who makes custom nodes would likely have to make their own blurring node, or sharpening node or canny node as that is just a very common operation, which is a component in larger setups.

**Comment by EllangoK** [comment]
@comfyanonymous any thoughts? If anything just add the `Blend` node, as almost every node collection has to implement their own blend node otherwise. It is just a very commonly shared operation.

**Comment by comfyanonymous** [comment]
make a PR with the nodes that don't need opencv and if it doesn't have any bugs I'll merge it. You can put the nodes that need cv2 in a seperate PR and I'll merge it once I officially add opencv to the dependencies.

**Pull request closed without merging**
