### PR TITLE
fix: ensure casting to torch.uint8

### PR DESCRIPTION
**Pull request by dnswd**
Fixes https://github.com/comfyanonymous/ComfyUI/issues/3539

### CODE REVIEW

**Comment by comfyanonymous** [comment]
if you do:
```
        latents_ubyte = latents_ubyte.to(device="cpu", dtype=torch.uint8, non_blocking=comfy.model_management.device_supports_non_blocking(latent_image.device))
        latents_ubyte = latents_ubyte.to(dtype=torch.uint8)
```
does it also work?

**Comment by dnswd** [comment]
At first the preview was showing 2 iterations, but then got a following python error. 
image

**Comment by dnswd** [comment]
I tried it again and the previews are just dots of rgb, but it doesn't seem to have any error

image

**Comment by dnswd** [comment]
Closed in favor of https://github.com/comfyanonymous/ComfyUI/pull/3583

**Pull request closed without merging**
