### PR TITLE
Add CORS middleware (allows for cross origin requests)

### LINKED ISSUE #397: CORS support in backend
I want to test a frontend on a different port than the backend on `localhost`, but get blocked by CORS.

Sadly however `aiohttp_cors` has a 5-year-old bug that breaks CORS support for POST requests (while GET works fine): https://github.com/aio-libs/aiohttp-cors/issues/155

I found that I had to use this code to work around it, but I couldn't get around modifying the backend https://github.com/home-assistant/core/issues/40513#issuecomment-700654471

### PR DESCRIPTION
**Pull request by EllangoK**
Should resolve #397. I did check myself, but @space-nuko you might to test it to double check.

One thing though is perhaps maybe make the `response.headers['Access-Control-Allow-Origin']` a parameter instead? I don't know how safe it is/isn't to allow all.

### CODE REVIEW

**Comment by missionfloyd** [comment]
https://github.com/aio-libs/aiohttp-cors

**Comment by missionfloyd** [comment]
https://github.com/aio-libs/aiohttp-cors

**Comment by EllangoK** [comment]
@missionfloyd Idk if you actually read #397, but space-nuko specifically mentions that there is an issue with CORS support for POST requests and you can see easily that package has not be properly updated in years. I think he has tried that solution and it didn't work. This however does seem to work. Also comfy as well agrees it is just a header we don't need a library for it.

**Comment by missionfloyd** [comment]
Sorry, I noticed that just now.

**Comment by EllangoK** [comment]
@comfyanonymous, I was trying to add to add an argument for allowed-origin, but I noticed that you are manually reading parameters. Imo I think you should switch to argparse as It is much easier to use as for example you can remove the tons of try excepts every time, and it adds new features like convenient default options.

I can submit a seperate PR doing this if you would be okay with it. I think it is much better, and most major python programs use it. It is included by default.

**Comment by comfyanonymous** [comment]
If you add argparse for the arguments in main.py that works.

Right now arguments are checked in the main.py and https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/model_management.py

I have wanted to clean things up in a way that makes sense and put it all in in the same place but have not had time to do that yet.

**Comment by space-nuko** [comment]
@EllangoK This works for me and is a lot simpler that what I was doing, thanks a lot!

**Comment by comfyanonymous** [comment]
Yeah this should be a command line option to enable it. Not a big security issue to have it on by default but I don't want to worry about it.

**Comment by EllangoK** [comment]
@comfyanonymous Yeah, i agree as well it should be off by default. I switched to argparse in #423, so let me know what you think of that. After it gets merged in I can add the cli argument for this herge.

**Comment by EllangoK** [comment]
Should work as a cli arg now.

`python main.py` does nothing.

`python main.py --cors` set allowed origins to all by default (`*`).

`python main.py --cors http://localhost:8000` set its to `http://localhost:8000`

**Comment by comfyanonymous** [comment]
I renamed the argument to --enable-cors-header because I thought that was more clear than just --cors

**Comment by Yash-Patidar** [comment]
How can i give multiple value on cors like  [ "http://localhost:3000" ,  "http://localhost:3001" ]

is it correct when try this "python main.py  --enable-cors-header   [ 'http://localhost:3000' ,  'http://localhost:3001' ] "

**Pull request merged**
