### PR TITLE
Added Google Drive mount feature to Colab Notebook.

### PR DESCRIPTION
**Pull request by ltdrdata**

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Good idea but keep in mind the notebook is also supposed to work on other services like paperspace so it should not import google stuff by default.

Is there any reason why you install triton?

**Comment by ltdrdata** [comment]
I just added triton because error message. It can be dropped if don't need.

**Comment by ltdrdata** [comment]
Oops. I added new feature mistakenly on same branch.

**Comment by ltdrdata** [comment]
I will close this PR and I will reopen separate branch to avoid mixing of features.

**Pull request closed without merging**
