### PR TITLE
Add the MULTIPLE_NODE = True attribute to the node to enable multiple…

### PR DESCRIPTION
**Pull request by chenbaiyujason**
… input lines with the ability to have empty input connections.

Currently, each input interface must be connected to a node, but I want to implement the function of merging multiple texts and allow input nodes to remain unconnected. For example, the node can merge up to 5 texts, but it can still execute when the user only connects two input nodes

Here's an example of a node:
```class Multiple_Combine_Text_String:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "text1": ("ASCII", {"default": '', "multiline": False}),
                "text2": ("ASCII", {"default": '', "multiline": False}),
                "text3": ("ASCII", {"default": '', "multiline": False}),
                "text4": ("ASCII", {"default": '', "multiline": False}),
                "text5": ("ASCII", {"default": '', "multiline": False}),
                "text6": ("ASCII", {"default": '', "multiline": False}),
                "text7": ("ASCII", {"default": '', "multiline": False}),
                "text8": ("ASCII", {"default": '', "multiline": False}),
            }
        }

    RETURN_TYPES = ("ASCII",)
    FUNCTION = "text_combine"
    MULTIPLE_NODE = True
    CATEGORY = "SC/Text"

    def text_combine(self, text1, text2, text3="", text4="", text5="", text6="", text7="", text8=""):
        #检查所有输入变量，如果不为空，则添加字符串
        texts = []
        for i in [text1, text2, text3, text4, text5, text6, text7, text8]:
            if i:
                texts.append(i)
        #返回texts变成的字符串，不要有间隔
        return (''.join(str(t) for t in texts),)
```

### CODE REVIEW

**Comment by chenbaiyujason** [comment]
> use optional @classmethod def INPUT_TYPES(cls): return { "required": { "text1": ("ASCII", {"default": '', "multiline": False}), "text2": ("ASCII", {"default": '', "multiline": False}), },{ "optional":{ "text3": ("ASCII", {"default": '', "multiline": False}), "text4": ("ASCII", {"default": '', "multiline": False}), "text5": ("ASCII", {"default": '', "multiline": False}), "text6": ("ASCII", {"default": '', "multiline": False}), "text7": ("ASCII", {"default": '', "multiline": False}), "text8": ("ASCII", {"default": '', "multiline": False}), { }

Wow, I didn't know it could be done like this! Thank you. Where else can I find related content, such as development documentation?

**Comment by omar92** [comment]
Sadly no documentation , i saw that on their scripts

**Comment by chenbaiyujason** [comment]
> Sadly no documentation , i saw that on their scripts
Thank you very much~

**Comment by missionfloyd** [comment]
> use optional @classmethod def INPUT_TYPES(cls): return { "required": { "text1": ("ASCII", {"default": '', "multiline": False}), "text2": ("ASCII", {"default": '', "multiline": False}), },{ "optional":{ "text3": ("ASCII", {"default": '', "multiline": False}), "text4": ("ASCII", {"default": '', "multiline": False}), "text5": ("ASCII", {"default": '', "multiline": False}), "text6": ("ASCII", {"default": '', "multiline": False}), "text7": ("ASCII", {"default": '', "multiline": False}), "text8": ("ASCII", {"default": '', "multiline": False}), { }

Doesn't seem to work, just makes all the inputs disappear.

**Comment by TashaSkyUp** [comment]
remove the PR? @chenbaiyujason

**Pull request closed without merging**
