### PR TITLE
feat:Latent Save/Load

### PR DESCRIPTION
**Pull request by ltdrdata**
I have implemented a simple Latent Save/Load nodes rely on **safetensor**. In consideration of future extensibility, I have also made it possible to store metadata together, similar to .png files. 

latent

### CODE REVIEW

**Comment by ltdrdata** [comment]
I made simpler this PR.
I'll make backend clipspace thing to another PR.

**Comment by ltdrdata** [comment]
Is it better to add metadata like this..?

"fileformat": "SD Latent"
"format_version": "1.0"
"created_by": "ComfyUI"

I hope this format becomes more generalized.

**Comment by InconsolableCellist** [comment]
I added similar here: https://github.com/comfyanonymous/ComfyUI/pull/576/files and the ability to interpolate latents together. I'm not sure the author is interested in this or similar features, however. I also added the ability to save, load, and interpolate attention weights from the middle nodes of the diffusion process, but only added it to one sampler (as it's a lot of work for each sampler, and if it doesn't get merged upstream it'll just remain a personal experiment).

**Comment by ltdrdata** [comment]
> I added similar here: https://github.com/comfyanonymous/ComfyUI/pull/576/files and the ability to interpolate latents together. I'm not sure the author is interested in this or similar features, however. I also added the ability to save, load, and interpolate attention weights from the middle nodes of the diffusion process, but only added it to one sampler (as it's a lot of work for each sampler, and if it doesn't get merged upstream it'll just remain a personal experiment). 

I know that. I had a memory of something I read on Mailfeed, and I was thinking about it. At that time, I thought it was for a discussion. And I found that your PR after submit.

TBH, the PR handles too many things within mixed at once. And it might takes long because it is little bit complex and requires much considerations in review.

The separated save/load feature doesn't need much changes. 

So, I suggest that remove save, load feature from that PR and concentrate the other feature. Then, you can handle the PR more easily. And it will helps reviewer, too.

**Comment by InconsolableCellist** [comment]
Oh yeah, the PR grew in size and I left it as a draft, and should really close it. I would've broken it out into individual features but I got the impression the maintainer wasn't interested in the stuff I was adding. Interpolating the attentions was a lot more interesting than the latents alone. But still pretty weird:

https://github.com/comfyanonymous/ComfyUI/assets/23345188/7ac73abc-9b1c-4f4e-bb7d-4bfa632cc422

**Comment by ltdrdata** [comment]
> Oh yeah, the PR grew in size and I left it as a draft, and should really close it. I would've broken it out into individual features but I got the impression the maintainer wasn't interested in the stuff I was adding. Interpolating the attentions was a lot more interesting than the latents alone. But still pretty weird:
> 
> https://github.com/comfyanonymous/ComfyUI/assets/23345188/7ac73abc-9b1c-4f4e-bb7d-4bfa632cc422
> 
> 

Oh it is interesting. But, It changes form of basic node. It is very serious thing.

I think you have to separate that feature.

How about make your own custom node and just PR for required manipulation code? But, you must review strongly, since it changes core code part.

**Comment by InconsolableCellist** [comment]
Yeah, merging the attention feature would be no small undertaking. It touched dozens of files and required hundreds of lines. I'll see what happens with your PR and maybe try contributing again if there's interest

**Comment by comfyanonymous** [comment]
I decided to make it behave more like the Save/LoadImage nodes since it was more logical for me. SaveLatent saves to output and LoadLatent loads from input by default but it supports the [output], etc... syntax just like the LoadImage node.

**Pull request merged**
