### PR TITLE
change slot colors to a more consistent palette

### PR DESCRIPTION
**Pull request by throwaway-mezzo-mix**
I am by no means an color expert, but the current slot colors are (in my opinion) not very visually pleasing. I've changed them to be a bit more consistent.
 
New colors

### CODE REVIEW

**Comment by jn-jairo** [comment]
I am colorblind, now everything looks the same, when I created the colors I specifically asked chat GPT to help me to create colors that are good for colorblind, and it worked, I could distinguish between the colors, now it is useless for me, maybe a yaml file for the colors would be a better solutions, like the one for the folders, so I can set the colors that are good for me.

**Comment by comfyanonymous** [comment]
I had a feeling something like this would happen... yes a way to specify different colour sets would be nice so everyone can be happy.

**Comment by jn-jairo** [comment]
> I had a feeling something like this would happen... yes a way to specify different colour sets would be nice so everyone can be happy.

I made a PR to add settings #284

**Comment by throwaway-mezzo-mix** [comment]
> I am colorblind, now everything looks the same, when I created the colors I specifically asked chat GPT to help me to create colors that are good for colorblind, and it worked, I could distinguish between the colors, now it is useless for me, maybe a yaml file for the colors would be a better solutions, like the one for the folders, so I can set the colors that are good for me.

Sorry about messing with the colors. I interpreted the "made ChatGPT choose the colors for me" more as placeholder colors than a palette that's good for colorblind people. The set of colors I used still looked fairly distinguishable to me as a non color-blind person. Apologies.

**Comment by jn-jairo** [comment]
> > I am colorblind, now everything looks the same, when I created the colors I specifically asked chat GPT to help me to create colors that are good for colorblind, and it worked, I could distinguish between the colors, now it is useless for me, maybe a yaml file for the colors would be a better solutions, like the one for the folders, so I can set the colors that are good for me.
> 
> Sorry about messing with the colors. I interpreted the "made ChatGPT choose the colors for me" more as placeholder colors than a palette that's good for colorblind people. The set of colors I used still looked fairly distinguishable to me as a non color-blind person. Apologies.

Don't worry, it is not your fault, the colors I added have a high contrast between them what helps with colorblind, I asked chat GPT for help because it is a lot of colors and it is difficult to create manually so many different colors keeping a high contrast between them.

I'm making a way to add other color palettes, so everyone can be happy, even who is not colorblind may rather use another color palette, so that is better for everyone.

**Pull request merged**
