### PR TITLE
Add individual models to cli args

### LINKED ISSUE #35: Is it possible to have checkpoints, embeddings, models, vae, etc. on an external drive?
I keep all of the above files on an external drive due to the large space requirements. Is there an option to select a custom directory where all my models are located, or even directly select a checkpoint/embedding/vae by absolute filesystem path?

### PR DESCRIPTION
**Pull request by ljleb**
Adds the following options to cli arguments:

```
	--checkpoint-dir path\to\dir	Add a path to a checkpoint directory.
	--config-dir path\to\dir	Add a path to a model config directory.
	--clip-dir path\to\dir		Add a path to a clip directory.
	--clip-vision-dir path\to\dir	Add a path to a clip vision directory.
	--controlnet-dir path\to\dir	Add a path to a controlnet or T2I checkpoint directory.
	--embedding-dir path\to\dir	Add a path to an embedding directory.
	--lora-dir path\to\dir		Add a path to a lora model directory.
	--style-model-dir path\to\dir	Add a path to a style model directory.
	--upscale-model-dir path\to\dir	Add a path to an upscale model directory.
	--vae-dir path\to\dir		Add a path to a vae directory.
```

Specifying the same option multiple times will add multiple directories instead of just one. For example, `--checkpoint-dir E:\sd\ckpt --checkpoint-dir D:\sd2\finetunes` will add both directories to the checkpoint search paths.

Feel free to edit the PR or ask for changes.

Closes #35

### CODE REVIEW

**Comment by ljleb** [comment]
This PR also normalizes the model names in config files to singular form, to minimize surprise when guessing config keys. Let me know if this is not wanted.

**Comment by ljleb** [comment]
Note that I changed the arguments to reflect the model tags used in folder_paths.py.

**Comment by comfyanonymous** [comment]
I tried this and there's a few issues. The first one is that if a extra_model_paths.yaml is present it just crashes on startup.
The second one is that UI doesn't work at all if you run it and open up: http://127.0.0.1:8188/

**Comment by ljleb** [comment]
With recent changes it is possible that the code no longer works. I'll take a look when I find some time.

**Comment by ljleb** [comment]
I personally don't need this anymore, feel free to add cli arguments in a new PR if you want.

**Pull request closed without merging**
