### PR TITLE
Update nodes.py to fix missing denoise lever on advanced KSampler

### PR DESCRIPTION
**Pull request by irakli-ff**
advanced KSampler was missing denoise lever making it impossible in any kind of img2img workflows

### CODE REVIEW

**Comment by ltdrdata** [comment]
The absence of denoise in `KSamplerAdvanced` is not a mistake; it is intentional. The `denoise` feature in `KSamplerAdvanced` is controlled through `start_at_step` and `end_at_step` parameters.

**Comment by irakli-ff** [comment]
> The absence of denoise in `KSamplerAdvanced` is not a mistake; it is intentional. The `denoise` feature in `KSamplerAdvanced` is controlled through `start_at_step` and `end_at_step` parameters.

I will do more testing and report back but I'm not sure if you can achieve parity in img2img workflows. Do you disable add_noise and skip the initial x steps to achieve the same results? and enable keeping leftover noise? Not sure but maybe you are right

**Comment by ltdrdata** [comment]
> > The absence of denoise in `KSamplerAdvanced` is not a mistake; it is intentional. The `denoise` feature in `KSamplerAdvanced` is controlled through `start_at_step` and `end_at_step` parameters.
> 
> I will do more testing and report back but I'm not sure if you can achieve parity in img2img workflows. Do you disable add_noise and skip the initial x steps to achieve the same results? and enable keeping leftover noise? Not sure but maybe you are right

I recommend translating and reading the content of the link provided at https://comfyui.creamlab.net/guides/f_KSamplerAdvanced_denoise

**Comment by irakli-ff** [comment]
> > > The absence of denoise in `KSamplerAdvanced` is not a mistake; it is intentional. The `denoise` feature in `KSamplerAdvanced` is controlled through `start_at_step` and `end_at_step` parameters.
> > 
> > 
> > I will do more testing and report back but I'm not sure if you can achieve parity in img2img workflows. Do you disable add_noise and skip the initial x steps to achieve the same results? and enable keeping leftover noise? Not sure but maybe you are right
> 
> I recommend translating and reading the content of the link provided at https://comfyui.creamlab.net/guides/f_KSamplerAdvanced_denoise

thanks for sharing this, looks like an amazing resource!

**Pull request closed without merging**
