### PR TITLE
Support non-square resolutions in Self-Attention Guidance.

### PR DESCRIPTION
**Pull request by shiimizu**
Fixes the exception thrown during the `mask.reshape()` on differing height and width of `x0`, as in the case with [Tiled Diffusion](https://github.com/shiimizu/ComfyUI-TiledDiffusion), where an image consisting of 2x3 or more tiles can be generated.

notes:
* floor division if a dimension is higher than the other, otherwise a ceiling division as done in the original code
* also used a more correct ceiling division than the one in `math`.

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Can you tell me which resolution was failing before this fix?

**Comment by comfyanonymous** [comment]
This didn't fix some resolutions I tried so I fixed it this way instead:
https://github.com/comfyanonymous/ComfyUI/commit/2c80d9acb9a542fef843954370390369093b6ac4
https://github.com/comfyanonymous/ComfyUI/commit/b4e915e74560bd2c090f9b4ed6b73b0781b7050e

**Comment by shiimizu** [comment]
Is it just me or has the issue not been fixed yet in that workflow? I still get the error:
```
  File "C:\Users\Peter\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Peter\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 263, in sampling_function
    cfg_result = fn(args)
                 ^^^^^^^^
  File "C:\Users\Peter\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_sag.py", line 150, in post_cfg_function
    degraded = create_blur_map(uncond_pred, uncond_attn, sag_sigma, sag_threshold)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Peter\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_sag.py", line 66, in create_blur_map
    mask.reshape(b, *mid_shape)
RuntimeError: shape '[1, 4, 3]' is invalid for input of size 9
```

**Comment by shiimizu** [comment]
Is it just me or has the issue not been fixed yet in that workflow? I still get the error:
```
File "C:\Users\mizu\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 272, in apply_model
out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\mizu\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 263, in sampling_function
cfg_result = fn(args)
             ^^^^^^^^
File "C:\Users\mizu\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_sag.py", line 150, in post_cfg_function
degraded = create_blur_map(uncond_pred, uncond_attn, sag_sigma, sag_threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\mizu\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_sag.py", line 66, in create_blur_map
mask.reshape(b, *mid_shape)
RuntimeError: shape '[1, 4, 3]' is invalid for input of size 9
```

**Pull request closed without merging**
