### PR TITLE
chore: add `prompt_id` into progress information

### PR DESCRIPTION
**Pull request by xbol0**
Add `prompt_id` to websocket progress information.

It's convenient to match the prompt when I hosted many ComfyUI backend.

### CODE REVIEW

**Comment by comfyanonymous** [comment]
using a global isn't the right way to do this.

**Comment by xbol0** [comment]
yes, i also think it's a bad way, but I only found one way to hijack the global hook:

https://github.com/mobfish-ai/ComfyUI/blob/feat_progress_prompt_id/main.py#L115

if modify the class `ProgressBar`, it must modify the sampler method and other nodes which use it at the same time.

it will cause more work, and made some irrelevant arguments passed in sampler nodes.

currently ComfyUI only suppported one task in progress, so it will not made chaos, just a bit bad code style

do you have other idea to fix it? thanks.

**Comment by chrisgoringe** [comment]
Maybe add `**kwargs` to the signature of ProgressBar's update methods and the call to hook, and make the hook insert the kwargs into the dictionary. Then any node using ProgressBar could send any additional information it wants. 

A node wanting to return the prompt_id then just needs to request "PROMPT" as a hidden input. It does involve a few more changes, but would give a more flexible solution for future expansion as a bonus.

**Comment by kelvinlong** [comment]
> using a global isn't the right way to do this.

@comfyanonymous  any better way to add the prompt_id within the progress message delivered by websocket? We really need the piece since we use API to demonstrate the rendering progress.

Thanks a lot!

**Comment by ElliottLester** [comment]
> > using a global isn't the right way to do this.
> 
> @comfyanonymous any better way to add the prompt_id within the progress message delivered by websocket? We really need the piece since we use API to demonstrate the rendering progress.
> 
> Thanks a lot!

I had a quick look at this and I think you can get what you need from the prompt_queue

 
    def hijack_progress(server):
        def hook(value, total, preview_image):
            comfy.model_management.throw_exception_if_processing_interrupted()
            current_queue = server.prompt_queue.get_current_queue() # returns a copy of the currently running queue
            if(len(current_queue) > 0):
                current_queue[0] then something like [client-id][list of prompts]

**Pull request closed without merging**
