### PR TITLE
New Note node

### PR DESCRIPTION
**Pull request by jwd-dev**
Multi-line note node. Very straight forward but useful to me and seemingly other users. (#468)

image

### CODE REVIEW

**Comment by jwd-dev** [comment]
Might want to also add a "reference image" node, basically Preview Image but it displays a file while editing, instead of loading on Queue Prompt

**Comment by comfyanonymous** [comment]
This is the kind of node that belongs in the frontend only.

**Comment by omar92** [comment]
if you can make it have default yellow color or another style will be great

**Comment by jwd-dev** [comment]
image
Pushing new front-end code shortly.

**Comment by jwd-dev** [comment]
@comfyanonymous @omar92 Notes are now front-end non serialized objects.

**Comment by comfyanonymous** [comment]
The contents of the node don't get saved for me, if I refresh the page the contents are gone.

**Comment by jwd-dev** [comment]
> The contents of the node don't get saved for me, if I refresh the page the contents are gone.

My apologies, I got the idea of a virtual node and the serialization process mixed up. They now save.

**Comment by Gorislav** [comment]
The next step is to add formatting. Color, style, font size, and the ability to insert hyperlinks)

**Comment by morphles** [comment]
I'll just say - good stuff, this notes node! :)

**Comment by jwd-dev** [comment]
I wonder if making the notes use markdown is something that could be nice.

**Pull request merged**
