### PR TITLE
[DRAFT] Support adding multiple outputs to a primitive widget

### PR DESCRIPTION
**Pull request by asagi4**
This generalizes the Primitive widget to support an arbitrary number of outputs.

It still defaults to one, but you can right-click and add outputs as needed. I didn't implement removal of slots, as you might as well just recreate the widget in that case.

There's something weird going on with size calculations though. Adding an output when something is connected causes the new slot to go under an existing widget until refresh.

I couldn't figure out why this happens, or how to get LiteGraph to recalculate the node size.

### CODE REVIEW

**Comment by asagi4** [comment]
Bah, I immediately found that this seems to be completely broken. Figures that it would happen only after making the PR...

**Comment by asagi4** [comment]
I'm not completely sure if that fix is fully correct either. It might call widget callbacks for all outputs even when only one is needed, but I'm not sure when that callback happens

**Comment by asagi4** [comment]
I'm really not a fan of the primitiveSlot mechanism to figure out which widget maps to which slot... I'd much prefer having a container widget so that the slot always unambiguously maps into a group of widgets in the node's widgets array, but that didn't seem like a trivial refactoring

**Comment by mcmonkey4eva** [comment]
Considering the `[DRAFT]`, the 4 month pause, the merge conflict, the messy code, and the questionable functionality described above, I'm going to close this for now.

If you'd like to re-attempt this in the future, please make sure (A) that it fully works before submitting and (B) that it all makes sense as a concept and is clearly explained in the PR's main description.

**Pull request closed without merging**
