### PR TITLE
Added Comfy Workflows Gallery link to README.md

### PR DESCRIPTION
**Pull request by thecooltechguy**
Hi! 👋

i'm building a free site for the ComfyUI community to share & discover thousands of workflows, so i wanted to ask if we could add a link to it in the README ([comfyworkflows.com](https://comfyworkflows.com)), so that others can benefit as well.

Thanks for all the great work on ComfyUI!

### CODE REVIEW

**Comment by WASasquatch** [comment]
I think the website needs to be flushed out some more. For example, most of the workflows are just scrapped, from private testing of development.

**Comment by thecooltechguy** [comment]
@WASasquatch thanks for your feedback! 🙏 

Since our launch 12 days ago, we’ve been rapidly iterating to make all of the ComfyUI workflows that people share, much more reproducible.

We constantly hear from users that it's very rare to be able to easily import & run other people's workflows w/o any issues.

Everyone has different local environments, portable vs. full installations, missing dependencies, custom node types, unknown checkpoints, etc. 

**_And often times these problems are not easily solvable, slowing down collaboration & learning._**

So, we're building a site where people can also share their knowledge around user-uploaded workflows (e.g., tips/tricks, how to run a particular workflow, etc.)

For ex, we're adding:
- user comments & profiles (should be live in ~1-2 days)
- upvotes/downvotes (should be live in ~3 days)
- important metrics like number of downloads (already done, and we’re adding more)

We're also developing a ComfyUI extension that would allow users to directly share their current art + workflow to the site from within ComfyUI, w/o needing an account (WIP screenshot attached lol). 

This would also record the various custom nodes + git versions used locally, which will hopefully help make a lot of the workflows that people share, much more reproducible.

Screenshot 2023-10-19 at 10 57 51 AM

Anyways, by adding a link to the README, we felt that we could build a very helpful, collective knowledge base around ComfyUI workflows a lot faster -- the more people that join the site & contribute, the more useful it would be for all ComfyUI users.

We’ve also been actively getting feedback from the community in [our Discord](https://discord.gg/s9rYn4PJhy) and using it to improve the site every day.

I really think ComfyUI has a very special approach to creating with generative models, and just want to make it accessible to a lot more people (esp. beginners like me lol)!

Would also love to hear your thoughts on any other particular things you'd like to see the site improve on! 🙏

**Comment by WASasquatch** [comment]
> @WASasquatch thanks for your feedback! 🙏
> 
> Since our launch 12 days ago, we’ve been rapidly iterating to make all of the ComfyUI workflows that people share, much more reproducible.
> 
> We constantly hear from users that it's very rare to be able to easily import & run other people's workflows w/o any issues.
> 
> Everyone has different local environments, portable vs. full installations, missing dependencies, custom node types, unknown checkpoints, etc.
> 
> **_And often times these problems are not easily solvable, slowing down collaboration & learning._**
> 
> So, we're building a site where people can also share their knowledge around user-uploaded workflows (e.g., tips/tricks, how to run a particular workflow, etc.).
> 
> For ex, we're adding:
> 
> * titles + descriptions (already done, [here](https://comfyworkflows.com/workflows/c8a964db-801e-4a17-bc73-5c06bf8b9c95) is an example workflow someone uploaded today)
> * user comments & profiles (should be live in ~1-2 days)
> * upvotes/downvotes (should be live in ~3 days)
> * important metrics like number of downloads (already done, and we’re adding more)
> 
> We're also developing a ComfyUI extension that would allow users to share their current art + workflow to the site directly from ComfyUI, w/o needing an account (WIP screenshot attached lol).
> 
> This would also record the various custom nodes + git versions used locally, which will hopefully help make a lot of the workflows that people share, much more reproducible.
> 
> Screenshot 2023-10-19 at 10 57 51 AM
> Anyways, by adding a link to the README, we felt that we could build a very helpful, collective knowledge base around ComfyUI workflows a lot faster -- the more people that join the site & contribute, the more useful it would be for all ComfyUI users.
> 
> We’ve also been actively getting feedback from the community in [our Discord](https://discord.gg/s9rYn4PJhy) and using it to improve the site every day.
> 
> I really think ComfyUI has a very special approach to creating with generative models, and just want to make it accessible to a lot more people (esp. beginners like me lol)!
> 
> Would also love to hear your thoughts on any other particular things you'd like to see the site improve on! 🙏

Sounds like you guys have a great concept starting. I will take a more in depth look when I have the time. 

You are correct in thinking ComfUI is a great tool. It l's the best approach for serious R&D and dynamic workflows for various tasks

**Comment by thecooltechguy** [comment]
Thanks @WASasquatch !

@comfyanonymous , would love your feedback on this PR! 👀

**Comment by comfyanonymous** [comment]
I think the best place for this is on the examples page since it's going to be more visible there.

**Comment by thecooltechguy** [comment]
hi @comfyanonymous , got it! it seems like there's already a pr for the examples page (https://github.com/comfyanonymous/ComfyUI_examples/pull/12), would it be possible to merge it?

thanks!

**Pull request closed without merging**
