### PR TITLE
improve: add descriptions for clip loaders

### PR DESCRIPTION
**Pull request by ltdrdata**
https://github.com/comfyanonymous/ComfyUI/discussions/5574

image

### CODE REVIEW

**Comment by Creative-comfyUI** [comment]
Thanks, Good Idea !

**Comment by Creative-comfyUI** [comment]
There is another problem with the combination of clip type. It doesn't work always with SDXL 
Some combination works other don't. We receive an error.

SDXL works only un dual clip  not in triple

**Comment by Creative-comfyUI** [comment]
Another difference using dualclip GGuf or dualclip with the same type of clip give different results.  There is a conversion ?  Hands are better with regular dualclip

**Comment by ltdrdata** [comment]
> There is another problem with the combination of clip type. It doesn't work always with SDXL Some combination works other don't. We receive an error.
> 
> SDXL works only un dual clip not in triple

Currently, TripleClipLoader is only being used in SD3.x.
That's why there's only SD3 in the hint.

Since GGUF is not part of ComfyUI Core, it's completely separate.
And since quantization is a method that reduces file size while accepting information loss, it naturally produces different results.

**Comment by kairin** [comment]
how about when using https://huggingface.co/BeichenZhang/LongCLIP-L (cos those who claims it works for them, generate really good outputs...)

i notice i get very bad generations with this.

so i simply stick to the normal clip-l and clip-g.

**Pull request merged**
