### PR TITLE
GFPGAN/ESRGAN

### PR DESCRIPTION
**Pull request by jac3km4**
Hi!
I like your project and consider it the most versatile SD UI out there. I'm not very experienced with Python, but I've added some new nodes locally and thought they might be useful to others.

This adds 2 new nodes, `ESRGAN` and `GFPGAN`. The `ESRGAN` node supports all the standard models and uses a list widget to pick them by name. They are then downloaded and cached on demand.
I couldn't figure out a clean way to plug-in face restore, so I ended up adding a `face_restore` input which is just a connection to the face restore model. I don't think the UI supports optional nodes, but it could be made optional in the future.

I've also built a convenience LORA widget that loads multiple LORAs based on a text prompt, I can open a PR for it if you think it's valuable: https://github.com/comfyanonymous/ComfyUI/compare/master...jac3km4:multilora?expand=1

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Thanks for the pull request.

I don't want comfyui to download stuff while it's running and would prefer if it was done in a separate setup script that the user can run.

Is it possible to include the ESRGAN and GFPGAN python code in the repo itself in a "extras" folder maybe? It shouldn't be too long if it's just the models.

**Comment by jac3km4** [comment]
@comfyanonymous
I've removed the download bit and replaced it with a small `configure.py` command-line file that can set up the model files. If no models are installed the nodes can't be used, which I think is the expected behavior.

**Comment by comfyanonymous** [comment]
A few things:

I get this when I try it on colab since it uses python 3.8.10:
``` Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import execution
  File "/content/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/content/ComfyUI/nodes.py", line 862
    match os.path.splitext(model)[0]:
          ^
SyntaxError: invalid syntax
```



Can you switch to a simpler library like this one for ESRGAN? https://github.com/Lornatang/ESRGAN-PyTorch

I'm having issues pip installing realesrgan and gfpgan on my system probably because some of their dependencies don't seem to play well with my pytorch. 


The GFPGAN and ESRGAN nodes should be completely separate from each other. There should be one node for applying ESRGAN to the image and one separate node for applying GFPGAN.

Also you should use the size of the weights and weight names in the model files to detect the type of model instead of the file names.


If you decide to make these changes I would like you to make a pull request for only the ESRGAN node first and then we can decide what to do with the GFPGAN.

**Comment by jac3km4** [comment]
The reason GFPGAN and ESRGAN are coupled here is because I think the optimal way to use GFPGAN is to do face restore on the original image and paste it on the upscaled background, but they could be used separately too, I'm OK with excluding GFPGAN from this PR.
I've had a look at [ESRGAN-PyTorch](https://github.com/Lornatang/ESRGAN-PyTorch), but it's not published to PIP and it doesn't seem to expose a convenient interface as a library, but maybe I'm missing something.

**Comment by comfyanonymous** [comment]
I would prefer using an ESRGAN library that only depends on pytorch, this one might also be a good choice since it's what the a1111 ui uses: https://github.com/victorca25/iNNfer

If it's not in pip copying the files to a subfolder of the comfy_extras folder is an option.

**Comment by jac3km4** [comment]
gonna close this PR, since I see you added the innfer upscaler on master

**Comment by Mshaoyang1991** [comment]
Please add GFPGAN it's really useful,Especially if you want to enlarge the picture,

**Comment by jac3km4** [comment]
@Mshaoyang1991 you can upscale on the master version with the `ImageUpscaleWithModel` node

**Pull request closed without merging**
