### PR TITLE
feat: pass settings items to backend on queue prompt

### PR DESCRIPTION
**Pull request by ltdrdata**
nodes can access settings value through hidden input "SETTINGS"

### CODE REVIEW

**Comment by ltdrdata** [comment]
> Could these be set per-node from the frontend instead? I don't know how well nodes globally changing settings by merely being included in the graph will work

You can access whole settings through adding input to nodes like this.
```
"hidden": {"settings": "SETTINGS"},
```

If you add global settings like this on frontend, node can access the setting value through ```settings['Comfy.ShowPreview']``` when the value is changed from defaultValue.

```
app.ui.settings.addSetting({
  id: "Comfy.ShowPreview",
  defaultValue: true,
  ...
)
```

**Comment by space-nuko** [comment]
Oh okay. So this could be expanded for per-node configuration from the frontend later

**Comment by comfyanonymous** [comment]
Yeah I'm not sure if this is the best way to solve this problem. I think nodes should also have clearly defined inputs.

**Comment by mcmonkey4eva** [comment]
The concept of "Hidden inputs" as a whole seems oppositional to the design goals of ComfyUI.

**Pull request closed without merging**
