### PR TITLE
improve: lightweight preview to reduce network traffic

### PR DESCRIPTION
**Pull request by ltdrdata**
To reduce network traffic in a remote environment, a lossy compression-based preview mode is provided for displaying simple visualizations in node-based widgets.
    
    * Added 'preview=[image format]' option to the '/view' API.
    * Updated node to use preview for displaying images as widgets.
    * Excluded preview usage in the open image, save image, mask editor where the original data is required.

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Wouldn't it be better to use webp instead of jpeg for the previews?

Is it normal that the loadimage previews are still in png format?

**Comment by ltdrdata** [comment]
> Wouldn't it be better to use webp instead of jpeg for the previews?
> 
> Is it normal that the loadimage previews are still in png format?

I have added webp as the default format. The preview of LoadImage should not be displayed as a PNG. It should only be saved as PNG when using the open image and save image functions. I haven't encountered such an issue in my tests so far. To make it easier to verify, I have added the grayscale option.

**Comment by space-nuko** [comment]
Could this use an LRU cache or similar?

**Comment by ltdrdata** [comment]
> Could this use an LRU cache or similar?

Do you meaning backend cache?

**Comment by space-nuko** [comment]
It might (I hope it doesn't) but if the computation isn't that expensive then it's fine

**Comment by comfyanonymous** [comment]
I think this should be an option turned off by default because when running locally it's always much more performant to serve the PNG files.

Sometimes the images in the input folder are already jpg or webp so in that case they should not be reencoded.

**Comment by ltdrdata** [comment]
> I think this should be an option turned off by default because when running locally it's always much more performant to serve the PNG files.
> 
> Sometimes the images in the input folder are already jpg or webp so in that case they should not be reencoded.

now default option is "turn off"
and you can set on global settings menu

**Pull request merged**
