### PR TITLE
AITemplate

### PR DESCRIPTION
**Pull request by hlky**
* AITemplate Loader
  * Applies model to aitemplate module 
* KSampler (AITemplate)
  * Wraps AITemplate module for use with kdiffusion

Requires unet module compiled with [`compile_alt.py`](https://github.com/facebookincubator/AITemplate/blob/main/examples/05_stable_diffusion/scripts/compile_alt.py) and/or [`compile_controlnet.py`](https://github.com/facebookincubator/AITemplate/blob/main/examples/05_stable_diffusion/scripts/compile_controlnet.py)

[Collection of precompiled modules](https://huggingface.co/hlky/aitemplate)

Usage UNet:
`Load Checkpoint` -> `Load AITemplate` -> `KSampler (AITemplate)`

Usage ControlNet:
`Load ControlNet Model` -> `Load AITemplate (ControlNet)` -> `Apply ControlNet`
+load appropriate Control UNet

https://github.com/comfyanonymous/ComfyUI/assets/106811348/d76fd188-8d06-41ba-a84b-e1e8b8a0f64f

image

Notes:
Needs ~~adjustment for 2.x support~~, ~~controlnet~~ etc may not work

### CODE REVIEW

**Comment by hlky** [comment]
Tested on a 4090 from runpod:tm:

~55it/s

50 steps

https://github.com/comfyanonymous/ComfyUI/assets/106811348/585931fc-a842-40d3-929d-a295d4477eea


20 steps


https://github.com/comfyanonymous/ComfyUI/assets/106811348/b203f8d5-b1f7-458b-889a-881cde6ecb35

**Comment by asagi4** [comment]
I gave this a quick test with your pre-compiled module and it is fast, but seems to ignore negative conditioning entirely, so output quality is terrible for me.

I'm not sure why the negative prompt gets ignored. The output only changes if I change the positive conditioning, and while negative conditioning does trigger a re-render, the output stays identical.

**Comment by asagi4** [comment]
That fixed it, indeed. The speedup is pretty crazy, especially for lower sizes. I generating 512x512 went from ~8.7it/s to 14.8 it/s. 768x768 went from 3.2it/s to 5it/s. (I have a 3060 too, on RHEL9)

Some other things I'm noticing with a bit more testing:
- Token merging doesn't seem to grant a speedup if AITemplate is used
- Batches larger than 1 throw an exception
- ControlNets don't cause errors, but they do nothing

**Comment by hlky** [comment]
>Token merging doesn't seem to grant a speedup if AITemplate is used

Tomesd is implemented in BasicTransformerBlock, I'll try adding it to AITemplate's BasicTransformerBlock but I'm not sure this will be able to work due to the compilation etc
>ControlNets don't cause errors, but they do nothing

ControlNet will require a module compiled for it and additional work on the AITemplateModelWrapper sampling side of things
>Batches larger than 1 throw an exception

The module I uploaded is only compiled for batch size 1, a module compiled for 64-1536 and up to batch size 4 is [here](https://huggingface.co/datasets/hlky/aitemplate/resolve/main/unet_bs.so)
As a general note; modules compiled for larger resolutions and larger batch size use more vram, but vram is consistent using the same amount regardless of the resolution and batch size of the generation

**Comment by ltdrdata** [comment]
I've tested on google colab. And I got this error message.

```
[01:53:43] model.h:29: Got error: no kernel image is available for execution on the device enum: 209 at constant_folder-generated.h: 109
[01:53:43] model_interface.cu:384: Error: Got error: no kernel image is available for execution on the device enum: 209 at constant_folder-generated.h: 109
```

issue

**Comment by hlky** [comment]
When the module is compiled, profilers are ran to determine the best algorithms to use. The modules I have shared are compiled on 3060/SM80+, so they won't work on SM75. Modules compiled on a SM75 gpu would work.

**Comment by ltdrdata** [comment]
> Author

Oh... Is it possible?

**Comment by hlky** [comment]
> Is it possible?

Yes.

**Comment by hlky** [comment]
[ControlNet soon:tm:](https://github.com/facebookincubator/AITemplate/pull/713)

**Comment by takoyaro** [comment]
Looking forward to seeing this merged

**Comment by hlky** [comment]
ControlNet support added, static sizes only for now

**ControlNet module must be used with specific ControlNet UNet**
**Using regular UNet module will not apply the control**

Modules for 512x512
[ControlNet](https://huggingface.co/datasets/hlky/aitemplate/resolve/main/controlnet_512_512.so)
[UNet](https://huggingface.co/datasets/hlky/aitemplate/resolve/main/unet_control_512_512.so)

Usage:
`Load ControlNet Model` -> `Load AITemplate (ControlNet)` -> `Apply ControlNet`

**Comment by jug-dev** [comment]
@comfyanonymous 

The individual behind the alias `hlky`, submitting this PR, has demonstrated actions that are against the spirit of open source, and against the sharing of stable diffusion based technology, I'm saddened that people like this exist in the world.

This individual issued a DCMA takedown notice against the project I started [hordelib](https://github.com/Haidra-Org/hordelib) which builds on top of ComfyUI, due to a cockup where one of the contributors removed a 4 letter alias from an AGPL copyright header. This DMCA takedown was issued without a single communication to me. Rather than simply reach out to me and discuss the issue which could have been easily resolved, they would rather attempt to takedown an entire volunteer online community which served to provide Stable Diffusion inference services to those who otherwise could not afford the expense of a modern GPU (i.e. Stable Horde).

https://github.com/github/dmca/blob/master/2023/05/2023-05-26-nataili.md

Prior to this, this individual had also deleted from Github another dependency that Stable Horde relied on in an attempt to take this community offline. 

This individual has demonstrated multiple actions seeking to shutdown stable diffusion based inference technology and specifically Stable Horde. It is obviously up to you if you think accepting submissions from such as individual is wise.

**Comment by hlky** [comment]
@jug-dev 

This pull request is unrelated to your issue, you are also free to reach out to me directly, alas you insist:

* db0 was instructed to cease using my code after I discovered a large portion of stable horde's traffic was CSAM
* eventually, hordelib is created, but my code is still used for several major components of hordelib
* however, license header is completely removed, this is in violation of the license agreement
* given the opportunity to resolve the matter, hordelib maintainers decide to mess around still and not reintroduce the original license header
* GitHub decided to takedown hordelib because maintainers did not comply

I have no intention of shutting down "stable diffusion based inference technology", I mean, you are literally commenting on a pull request where I've implemented AITemplate **for the community**.

**Comment by jshph** [comment]
@hlky which ControlNet model did you compile with AIT? I tried loading a binary which I compiled from `"lllyasviel/sd-controlnet-canny"`. However, this produces some errors. I get different errors when I load `lllyasviel/ControlNet-v1-1`.

I kind of wonder if this is due to how ComfyUI modifies the original lllyasviel ControlNet code whereas AIT compiles with diffusers/controlnet code.

Thanks a lot!

**Comment by hlky** [comment]
@jshph 

I compiled ControlNet with `[lllyasviel/sd-controlnet-canny](https://huggingface.co/lllyasviel/sd-controlnet-canny/)` but any model that works with Comfy should work, for example I've used [this one](https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_canny.pth).

Precompiled modules can be found on [huggingface](https://huggingface.co/datasets/hlky/aitemplate)

I've just pushed some fixes for ControlNet [here](https://github.com/hlky/AIT), there had been some changes to Comfy's controlnet code, that repo is the new home of my AITemplate code. If you still have issues feel free to create an issue over on that repo with the errors that you're experiencing.

Refer to the following image for how the graph should be set up. ControlNet is loaded as normal and fed into `Load AITemplate (ControlNet), a matching unet_control is also required, this needs the model fed from load checkpoint into `Load AITemplate` which then goes to KSampler.

image

**Comment by jshph** [comment]
Many thanks @hlky! I'll check out your work here, I'm sure it will be very helpful to get ControlNet/Comfy up and running.

**Comment by CyberTimon** [comment]
Can this be reimplemented for SD XL? Because SDXL is quite slow..

**Comment by 2blackbar** [comment]
IS it me or it does not work with batches , works with only one image per generation

**Pull request closed without merging**
