### PR TITLE
Add in torch.compile support for model loading

### PR DESCRIPTION
**Pull request by simonlui**
Note that if you can rework your workflow, AI Template or other similar custom nodes are still going to be faster if you can get them running and run them. However, this gives options for standard workflows to get speedups without significant reworking of the workflows themselves. This should work for most nodes and both SD 1.5 and SDXL although some extra or non-main nodes may be excluded from what I glossed over in the codebase, but I could be wrong. Default options can be changed if needed but I chose the most sensible ones. Needs testing before it goes in with the different backends in Pytorch itself. I can only advocate for the "ipex" Intel backend which works for me. Addresses #1097.

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Last time I tested torch.compile just changing the sampling resolution broke it.

**Comment by asagi4** [comment]
Couldn't this be done pretty neatly with a node instead of command line args? It could set a model option in the model patcher to trigger compilation, and depend on any inputs that need to trigger recompilation.

**Comment by simonlui** [comment]
@comfyanonymous Sorry, are you talking about doing latent upscaling here and running it through a Ksampler afterwards would break or are you talking about using a resolution not baked into the model i.e. instead of 512x512, you use 768x768 for SD 1.5 and things would break? In either of those scenarios, I have not had any issues.

@asagi4 It is possible but this again is meant to be transparent to the user in a backwards compatible fashion for workflows. If you have to use a new node that does this to gain performance, I don't see why you wouldn't take the extra step to use custom nodes out there like AI Template which takes it a step further code-wise and gives you more performance.

**Comment by comfyanonymous** [comment]
I tried it and it doesn't actually do anything. For it to do something the torch.compile needs to be called on the real_model.diffusion_model (the actual unet model) then it will actually torch.compile it which will speed things up a bit but the issue is that any change in sampling resolution will break it.

**Comment by simonlui** [comment]
Okay I see what you mean. I will need to think about this more deeply.

**Comment by simonlui** [comment]
So the core issue to even getting it work was eigenops not being compatible with torch.compile. Installing the latest [7.0.0 RC2](https://pypi.org/project/einops/0.7.0rc2/) package which purports torch.compile compatibility [here](https://github.com/arogozhnikov/einops) allowed things to run without running into any issues when using the changes I made... That is, after over 3-4 minutes of waiting. And then some more time to wait for the refiner. But eventually, the time taken.
```shell
Prompt executed in 486.19 seconds
```
So over 8 minutes of waiting for a single image which is a negative speedup compared to normal. I'm hoping this is Intel specific but boy does that not bode well for other cards given my experience. But it does work and the image generates fine.
Screenshot from 2023-08-24 23-36-41
But the usefulness of a patch like this is probably going to have to wait on upstream getting much better.
@asagi4 You were mostly right after all, I'm sorry I didn't take your suggestion into deeper consideration given my code now is close to where you suggested things should take place. This is probably best handled as arguments to the Ksampler if we don't want to disrupt workflows if it had to be implemented at all or in a custom node like you said. I wasn't thinking deeply enough about model modifications like you were. However, I don't think it's wise to do it in the model patcher until all the modifications are finalized and the model has been sent off to the Ksampler.

**Comment by kasper93** [comment]
> So over 8 minutes of waiting for a single image which is a negative speedup compared to normal.

This would require proper caching system and reuse the already compiled modes. Of course the compilation every time will be slower.

**Comment by simonlui** [comment]
> This would require proper caching system and reuse the already compiled modes. Of course the compilation every time will be slower.
I want to clarify that even without the compilation step, it would be slower than usual on my setup running both sampling steps compared to normal even with Intel optimizations on. I would be interested to know if that would still be the case with a Nvidia GPU.

**Comment by asagi4** [comment]
I wonder, is it possible to cache compiled models on disk and reuse them? There's a fork of the AITemplate nodes that does exactly that for AITemplate modules here: https://github.com/gameltb/AIT. Compilation is slow, but it turns out that you can change models and apply the new weights to a pre-compiled AITemplate module without triggering a recompilation. Can torch.compile do something like this?

**Comment by simonlui** [comment]
It should, but I don't think it's working for whatever reason with the models I was using. Probably some upstream problems again. I do know it does work with Diffuspr though with other UIs.

**Comment by mcmonkey4eva** [comment]
This was added as a special node recently!

**Pull request closed without merging**
