### PR TITLE
Cleanup if idle (w/ a flag `use_maximum_caching` to tell the server whether it should unload and free memory)

### PR DESCRIPTION
**Pull request by liusida**
Hi, it's me again. I previously submitted a PR regarding cleaning up cache (related to #3192) but have since closed it due to overlooking some crucial details.

After further tweaking, I still believe we should minimize memory usage when ComfyUI is used as a B/S (Browser/Server) application. However, based on your feedback about users who operate the server side alone, I have introduced a new variable called `use_maximum_caching` and an endpoint `/set_maximum_caching`. This allows API callers to configure the server to maximize cache preservation.

The main change is in the `server.py`. By default, it assumes a B/S application mode, as this is the most common usage scenario for ComfyUI users, who may not have the capability to optimize the system. In this mode, the server will free up VRAM when there are no websocket connections and the queue is empty.

API users wishing to preserve cache can set `use_maximum_caching` to True. This adjustment, as demonstrated in `script_examples/basic_api_example.py`, prevents the server from clearing cache when idle.

Please consider this change. Thanks.

P.S. There is a typo in `main.py` which is unrelated to this issue; I apologize for the confusion caused by including that commit in this PR. I'm unsure how to remove it.

### CODE REVIEW

**Comment by ycwdyy** [comment]
Using your modified code, I found that after the operation was completed, the running memory was not effectively released.

**Comment by liusida** [comment]
> Using your modified code, I found that after the operation was completed, the running memory was not effectively released.

It also checks for whether the ws connections are all closed. So have you closed your browser, please?

**Comment by liusida** [comment]
or, maybe at least, as an alternative, we can add callback functions after processing queue and after ws connection closed, so that custom nodes can properly do the clean up if people need it?

**Comment by ycwdyy** [comment]
> > Using your modified code, I found that after the operation was completed, the running memory was not effectively released.
> 
> It also checks for whether the ws connections are all closed. So have you closed your browser, please?

I have closed the browser and used the API to call, and found that the above method cannot effectively release the running memory, and will continue to superimpose and eventually cause the server running memory to overflow.

**Comment by liusida** [comment]
> > > Using your modified code, I found that after the operation was completed, the running memory was not effectively released.
> > 
> > 
> > It also checks for whether the ws connections are all closed. So have you closed your browser, please?
> 
> I have closed the browser and used the API to call, and found that the above method cannot effectively release the running memory, and will continue to superimpose and eventually cause the server running memory to overflow.

Hi, @ycwdyy, there are several things you can check:

1. Which repo and branch are you using? You can go to your folder and do `git status` and `git remote -v`.
2. Which system are you using? Linux or Windows?
3. Do you see the message `unload_models and free_memory` in your ComfyUI console? since this will be printed everytime the program is trying to unload models and free memory.
4. You mentioned using "the API to call". Could you specify which API were referring to? Since there's no need to call any API within my implementation, this clarification is important.

(btw, You can use Chinese to describe your issue in detail if that's easier for you, so that I can offer my help.)

**Comment by ycwdyy** [comment]
图生图
我这边使用的是ubuntu(20.04.2)系统进行搭建的，我手动添加了你的修改代码，服务跑完也执行了相关代码，也看到了unload_models and free_memory，但是发现还是不能有效的释放运行内存，每次执行都会堆加运行内存。然后使用原本系统提供的/free 这个释放的API接口也不起作用。

**Comment by liusida** [comment]
> 我这边使用的是ubuntu(20.04.2)系统进行搭建的，我手动添加了你的修改代码，服务跑完也执行了相关代码，也看到了unload_models and free_memory，但是发现还是不能有效的释放运行内存，每次执行都会堆加运行内存。然后使用原本系统提供的/free 这个释放的API接口也不起作用。

I've discovered that using Restart in ComfyUI-Manager on Linux can cause a memory leak:
https://github.com/ltdrdata/ComfyUI-Manager/issues/576

Have you happened to use Restart in ComfyUI-Manager recently (maybe after installing some custom nodes)?

我发现在Linux上使用ComfyUI-Manager的Restart功能可能会导致内存泄漏：
https://github.com/ltdrdata/ComfyUI-Manager/issues/576

你最近有没有使用ComfyUI-Manager的Restart功能（可能是在安装了一些自定义节点之后）？

**Comment by ycwdyy** [comment]
> > 我这边使用的是ubuntu(20.04.2)系统进行搭建的，我手动添加了你的修改代码，服务跑完也执行了相关代码，也看到了unload_models and free_memory，但是发现还是不能有效的释放运行内存，每次执行都会堆加运行内存。然后使用原本系统提供的/free 这个释放的API接口也不起作用。
> 
> I've discovered that using Restart in ComfyUI-Manager on Linux can cause a memory leak: [ltdrdata/ComfyUI-Manager#576](https://github.com/ltdrdata/ComfyUI-Manager/issues/576)
> 
> Have you happened to use Restart in ComfyUI-Manager recently (maybe after installing some custom nodes)?
> 
> 我发现在Linux上使用ComfyUI-Manager的Restart功能可能会导致内存泄漏： [ltdrdata/ComfyUI-Manager#576](https://github.com/ltdrdata/ComfyUI-Manager/issues/576)
> 
> 你最近有没有使用ComfyUI-Manager的Restart功能（可能是在安装了一些自定义节点之后）？

最近没有进行相关节点的restart功能，都是进行服务停止后再重新启动的，那这个问题整体是因为系统的问题吗，导致释放不了运行内存。

**Comment by liusida** [comment]
> 最近没有进行相关节点的restart功能，都是进行服务停止后再重新启动的，那这个问题整体是因为系统的问题吗，导致释放不了运行内存。

Out of curiosity, was everything working normally before you changed the source code? I suspect that it's not related to the modification...

出于好奇，你改变源代码之前一切都正常工作吗？我怀疑可能这和修改无关...

**Comment by ycwdyy** [comment]
> > 最近没有进行相关节点的restart功能，都是进行服务停止后再重新启动的，那这个问题整体是因为系统的问题吗，导致释放不了运行内存。
> 
> Out of curiosity, was everything working normally before you changed the source code? I suspect that it's not related to the modification...
> 
> 出于好奇，你改变源代码之前一切都正常工作吗？我怀疑可能这和修改无关...

额，改代码之前就是有释放不了运行内存的问题，我以为你这改动代码能解决相关问题~~

**Comment by liusida** [comment]
> > > 最近没有进行相关节点的restart功能，都是进行服务停止后再重新启动的，那这个问题整体是因为系统的问题吗，导致释放不了运行内存。
> > 
> > 
> > Out of curiosity, was everything working normally before you changed the source code? I suspect that it's not related to the modification...
> > 出于好奇，你改变源代码之前一切都正常工作吗？我怀疑可能这和修改无关...
> 
> 额，改代码之前就是有释放不了运行内存的问题，我以为你这改动代码能解决相关问题~~

Sorry, if invoking /free does not release it, then you need to submit another issue to describe the problem in detail. This PR only solves the issue of freeing up resources using the existing interface when no one is using the system.

不是的，如果调用了 /free 也释放不了那需要另外提交一个issue详细描述一下问题。这个PR是解决在无人使用时利用原有接口释放资源。

**Comment by ycwdyy** [comment]
> > > > 最近没有进行相关节点的restart功能，都是进行服务停止后再重新启动的，那这个问题整体是因为系统的问题吗，导致释放不了运行内存。
> > > 
> > > 
> > > Out of curiosity, was everything working normally before you changed the source code? I suspect that it's not related to the modification...
> > > 出于好奇，你改变源代码之前一切都正常工作吗？我怀疑可能这和修改无关...
> > 
> > 
> > 额，改代码之前就是有释放不了运行内存的问题，我以为你这改动代码能解决相关问题~~
> 
> Sorry, if invoking /free does not release it, then you need to submit another issue to describe the problem in detail. This PR only solves the issue of freeing up resources using the existing interface when no one is using the system.
> 
> 不是的，如果调用了 /free 也释放不了那需要另外提交一个issue详细描述一下问题。这个PR是解决在无人使用时利用原有接口释放资源。

嗯嗯 好的，感谢大佬的答疑解惑。貌似也有相关问题的issue，但是貌似并没有提供相关的解决方案，我也先去提交个issue看看~

**Pull request closed without merging**
