### PR TITLE
add prettier formatter config file

### PR DESCRIPTION
**Pull request by FaridSafi**
To run prettier on the `web` folder, the easiest way is to have [node](https://nodejs.org/en) installed on the system then to :
`npx prettier --config ./web/.prettierrc --write ./web`

It will format all `.js` `.html` `.json` and `.css` files.
I would recommend to run some tests after formatting a whole project (sometimes JavaScript syntax can be ambiguous).

### CODE REVIEW

**Comment by FaridSafi** [comment]
Usually Prettier is used directly in the IDE (e.g. [Prettier for VSCode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)) to Format on Save.
Personally I can't imagine starting a new project without Prettier, it makes development faster and safer. I would also recommend to set up [eslint](https://github.com/eslint/eslint) in the project. I think it's more problematic to have a codebase with non-consistent syntax.
I confirm that big open source projects use it in production (e.g. [Vercel](https://github.com/vercel/next.js), [React](https://github.com/facebook/react), etc.)

**Comment by WASasquatch** [comment]
eslint also has it's own formatting, that is less destructive. Also, I really hate VSCodes idea of syntax. I've been getting pushes from it from people and it just destroys the files. Arbitrarily linebreaks that don't even follow PEP on vertical alignment, and make human readability a chore, and also trick my editor into doing the wrong indentations.

**Comment by FaridSafi** [comment]
I never experienced or heard about the concerns you are talking about. Maybe you should try [Prettier for VIM](https://github.com/prettier/vim-prettier)

Your decision @comfyanonymous

**Comment by WASasquatch** [comment]
> I never experienced or heard about the concerns you are talking about. Maybe you should try [Prettier for VIM](https://github.com/prettier/vim-prettier)
> 
> Your decision @comfyanonymous

Pretty sure people have written their rants and most reviews cons persist to open source collaborations and how they can cause issues, like diff and indentation

https://antfu.me/posts/why-not-prettier
https://blog.scottlogic.com/2019/12/05/prettier-tips-and-tricks-for-large-codebases.html

The issue trackers for it and vscode also have a lot issues pertaining to formatting issues and triggering error states.

**Comment by pythongosssss** [comment]
I think the aim of this prettier PR was for the frontend code rather than for prettier + python. I personally think having a standard style is very useful as we get more contributors - whether this is prettier or eslint or whatever.

**Comment by WASasquatch** [comment]
> I think the aim of this prettier PR was for the frontend code rather than for prettier + python. I personally think having a standard style is very useful as we get more contributors - whether this is prettier or eslint or whatever.

The whitespace and linebreak issues it introduces is universal to any ASCII file it formats.

**Comment by FaridSafi** [comment]
I don't know who told you Prettier is not for dev but he lied.
I don't think there is a whitespace issue because I added `"useTabs": true` to stick to current format.

**Comment by WASasquatch** [comment]
> I don't know who told you Prettier is not for dev but he lied. I don't think there is a whitespace issue because I added `"useTabs": true` to stick to current format.

That's not what creates the issue, though. For example if the file has a line with one space on it that 5 people have that are using it in their work, and one person formats and merges, it's highly likely the code won't be mergeable because of white space conflicts. GitHub sees these changes as possible syntax corrections is my guess so it will often require manual fixing. 

And yes prettier is inherently meant at production unless you are configuring your editor. Which then implies people all using editors compatible with prettier to have uniform output. If you aren't using a editor with prettier you would format your production. For collaboration you don't often see this schema enforceable without exclusion of people just cause they don't use a supporting IDE and will introduce files that need formatting.

**Comment by pythongosssss** [comment]
The prettier (or anything i dont mind what, just something to try and maintain some consistency) config can exist, people who have it will then have it formatted, people without wont, and then periodically the `format all the things` command can be run? If comfy/we decide that it isn't working well, we can remove it?

I dont think it is a call to reject all PRs that arent formatted with prettier, its a nice to have to keep things somewhat tidy

**Comment by huchenlei** [comment]
Done in the new TS frontend repo. https://github.com/Comfy-Org/ComfyUI_frontend/pull/81

**Pull request closed without merging**
