### PR TITLE
update Md File - Create unofficial third-party app reference material

### PR DESCRIPTION
**Pull request by loeaf**
created and added unofficial free services provided using comfyui.
It can indicate that Comfyui is utilized by many other sites and improve credibility of the tool.

### CODE REVIEW

**Review by shawnington — COMMENTED** [review]
This is just advertisement for websites you probably own. 

No.

**Comment by loeaf** [comment]
> This is just advertisement for websites you probably own.
> 
> No.
why no?

The services on the comfyui site are open source, and open source has developed through disclosure, sharing, and communication.

https://github.com/orgs/ComfyPrompt/repositories

I hope people don't just see it as a promotion.

Open source develops through disclosure, sharing, and feedback.

**Comment by shawnington** [comment]
> > This is just advertisement for websites you probably own.
> > No.
> > why no?
> 
> The services on the comfyui site are open source, and open source has developed through disclosure, sharing, and communication.
> 
> https://github.com/orgs/ComfyPrompt/repositories
> 
> I hope people don't just see it as a promotion.
> 
> Open source develops through disclosure, sharing, and feedback.

There is a vibrant open source community surrounding this, you have never contributed. You trying to SEO your links into the repo isn't going to happen.

**Comment by loeaf** [comment]
> > > This is just advertisement for websites you probably own.
> > > No.
> > > why no?
> > 
> > 
> > The services on the comfyui site are open source, and open source has developed through disclosure, sharing, and communication.
> > https://github.com/orgs/ComfyPrompt/repositories
> > I hope people don't just see it as a promotion.
> > Open source develops through disclosure, sharing, and feedback.
> 
> There is a vibrant open source community surrounding this, you have never contributed. You trying to SEO your links into the repo isn't going to happen.

I think I'm being too critical.

I don't want to seo a link to the repository, I just wrote it for reference since it is open source.

Although said never contributed to an open source community, it can be a first for anyone.

I consider making my source code public as a contribution.

I think the merge may be rejected, but it is not easy to modify the comfyui code and make it public by modifying the code so that it can be visualized as an iframe on the web.

I think it would be nice if readMe had a table of contents that simply revealed cool examples created through comfyui.

**Comment by shawnington** [comment]
> > > > This is just advertisement for websites you probably own.
> > > > No.
> > > > why no?
> > > 
> > > 
> > > The services on the comfyui site are open source, and open source has developed through disclosure, sharing, and communication.
> > > https://github.com/orgs/ComfyPrompt/repositories
> > > I hope people don't just see it as a promotion.
> > > Open source develops through disclosure, sharing, and feedback.
> > 
> > 
> > There is a vibrant open source community surrounding this, you have never contributed. You trying to SEO your links into the repo isn't going to happen.
> 
> I think being too critical.
> 
> I don't want to seo a link to the repository, I just wrote it for reference since it is open source.
> 
> Although said never contributed to an open source community, it can be a first for anyone.
> 
> I consider making my source code public as a contribution.
> 
> I think the merge may be rejected, but it is not easy to modify the comfyui code and make it public by modifying the code so that it can be visualized as an iframe on the web.
> 
> I think it would be nice if readMe had a table of contents that simply revealed cool examples created through comfyui.

Im 3 for 3 for commits, if you commit code that solves an exiting problem well, it will be included into the main branch. If you try and modify and .md file to include external links it wont.

**Comment by loeaf** [comment]
> > > > > This is just advertisement for websites you probably own.
> > > > > No.
> > > > > why no?
> > > > 
> > > > 
> > > > The services on the comfyui site are open source, and open source has developed through disclosure, sharing, and communication.
> > > > https://github.com/orgs/ComfyPrompt/repositories
> > > > I hope people don't just see it as a promotion.
> > > > Open source develops through disclosure, sharing, and feedback.
> > > 
> > > 
> > > There is a vibrant open source community surrounding this, you have never contributed. You trying to SEO your links into the repo isn't going to happen.
> > 
> > 
> > I think being too critical.
> > I don't want to seo a link to the repository, I just wrote it for reference since it is open source.
> > Although said never contributed to an open source community, it can be a first for anyone.
> > I consider making my source code public as a contribution.
> > I think the merge may be rejected, but it is not easy to modify the comfyui code and make it public by modifying the code so that it can be visualized as an iframe on the web.
> > I think it would be nice if readMe had a table of contents that simply revealed cool examples created through comfyui.
> 
> Im 3 for 3 for commits, if you commit code that solves an exiting problem well, it will be included into the main branch. If you try and modify and .md file to include external links it wont.

okay. thank you

**Pull request closed without merging**
