### PR TITLE
Rename `ImageCrop` to `Image Crop`

### PR DESCRIPTION
**Pull request by KoreTeknology**
Feedback
-
Nodes menu has inconsistency in names, some with spaces between words, other not. i made some minor changes on our local installations (students project). This is something important for the next releases. The actual menu push developers to add their category into the top level, what is not the best option for the users to search for a specific category, if the category exists into various levels.

also, it must be considered that developers would have a guided structure to include their custom nodes packages into existing categories (until the node requires a new one) for consistency and easy search.

Mockup
-
By re-arranging the main node menu, we give to developers a way to inlude their custom nodes in a practical manner.

menu_comfy_review

Pull request & future development
-
this first pull is about the Image Crop node, to give an overview on my next requests. if accepted, i will work make a complete proposal for this menu. i want to contribute to this project as a developer, mainly because my students are giving me a lot of user feedbacks and i believe it can serve the purpose of the community.
if you want to check my profil: https://www.linkedin.com/in/urieldeveaud/
thank you

### CODE REVIEW

**Comment by huchenlei** [comment]
Please file frontend related issues in the frontend repo. Thanks!

https://github.com/Comfy-Org/ComfyUI_frontend

**Review by huchenlei — CHANGES_REQUESTED** [review]
`Image Crop` you are changing is the node unique id, which is not supposed to be modified. You should do
```python
NODE_DISPLAY_NAME_MAPPINGS = {
    "ImageCrop": "Image Crop"
}
```
instead to modify display name.

**Comment by KoreTeknology** [comment]
> ```python
> NODE_DISPLAY_NAME_MAPPINGS = {
    "ImageCrop": "Image Crop"
}
> ```

that´s right! 
Should i add the line to nodes.py in a new pull?  it not exists

**Review by huchenlei — APPROVED** [review]

**Comment by huchenlei** [comment]
@comfyanonymous PTAL. This is a straightforward change.

**Pull request merged**
