### PR TITLE
Group menu option select nodes

### PR DESCRIPTION
**Pull request by jn-jairo**
This PR adds the menu option to select the nodes inside the group.

### CODE REVIEW

**Comment by xueqing0622** [comment]
How about add "Grouping of selected nodes"

**Comment by jn-jairo** [comment]
> Nice feature, thx for your work, How about add "Grouping of selected nodes", give a group to all select nodes, auto resize for all select nodes, no need to drag and resize.

Done #1763 just waiting the approval, I did some extra options too, now it is easy to create and edit groups without drag and resize.

Good idea 👍🏻

**Comment by xueqing0622** [comment]
wow, cool, thank you!! another good feature!

How about when right mouse button group , the edit group,sub menu,  move out  the sub menu like this:
image


And if I mouse arrow focus on group, press delete to quick delete group group.( or can select group to press delete to delete)

Thx again.

**Comment by xueqing0622** [comment]
Good point, thanks for the modification of the grouping.
have a nice day,

**Pull request merged**
