### PR TITLE
Issue 741: Fix background

### PR DESCRIPTION
**Pull request by reaper47**
This solves issue #741. You many need to perform a hard refresh to clear your browser cache for changes to take effect.

### CODE REVIEW

**Comment by comfyanonymous** [comment]
I think the white background is a bit too white because I can barely see the nodes.

**Comment by reaper47** [comment]
The nodes are now more visible:
lighter

We can update the CLEAR_BACKGROUND_COLOR to a hex color between `white` and `lightgrey` if the background is a bit too dark for the light theme.

**Comment by WASasquatch** [comment]
I don't see the image is super dark? Is the scaling issue fixed? Or just your browser rendering different? If just your browser it may be fixable for Firefox and other browsers with [different rendering mode](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering).

**Comment by reaper47** [comment]
The creator of litegraphjs [wrote](https://github.com/jagenjo/litegraph.js/issues/276) that the reason why the image is super dark when you zoom out is because the pattern texture fades to transparent the further you zoom out.

**Pull request merged**
