### PR TITLE
Add MODULE_NODE_MAPPINGS dictionary

### PR DESCRIPTION
**Pull request by WASasquatch**
MODULE_NODE_MAPPINGS contains a module to node mapping of all nodes within the instance of ComfyUI. 

This sorted information is beneficial for third party development and potentially future ComfyUI features.

Example of my instance:

```
{   'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_canny.py': {   'Canny': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_canny.Canny'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_clip_sdxl.py': {   'CLIPTextEncodeSDXL': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_clip_sdxl.CLIPTextEncodeSDXL'>,
                                                                                   'CLIPTextEncodeSDXLRefiner': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_clip_sdxl.CLIPTextEncodeSDXLRefiner'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_freelunch.py': {   'FreeU': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_freelunch.FreeU'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_hypernetwork.py': {   'HypernetworkLoader': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_hypernetwork.HypernetworkLoader'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_latent.py': {   'LatentAdd': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_latent.LatentAdd'>,
                                                                                'LatentMultiply': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_latent.LatentMultiply'>,
                                                                                'LatentSubtract': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_latent.LatentSubtract'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_mask.py': {   'CropMask': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.CropMask'>,
                                                                              'FeatherMask': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.FeatherMask'>,
                                                                              'GrowMask': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.GrowMask'>,
                                                                              'ImageColorToMask': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.ImageColorToMask'>,
                                                                              'ImageCompositeMasked': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.ImageCompositeMasked'>,
                                                                              'ImageToMask': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.ImageToMask'>,
                                                                              'InvertMask': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.InvertMask'>,
                                                                              'LatentCompositeMasked': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.LatentCompositeMasked'>,
                                                                              'MaskComposite': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.MaskComposite'>,
                                                                              'MaskToImage': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.MaskToImage'>,
                                                                              'SolidMask': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_mask.SolidMask'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_model_merging.py': {   'CLIPMergeSimple': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_model_merging.CLIPMergeSimple'>,
                                                                                       'CheckpointSave': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_model_merging.CheckpointSave'>,
                                                                                       'ModelMergeAdd': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_model_merging.ModelAdd'>,
                                                                                       'ModelMergeBlocks': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_model_merging.ModelMergeBlocks'>,
                                                                                       'ModelMergeSimple': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_model_merging.ModelMergeSimple'>,
                                                                                       'ModelMergeSubtract': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_model_merging.ModelSubtract'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_post_processing.py': {   'ImageBlend': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_post_processing.Blend'>,
                                                                                         'ImageBlur': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_post_processing.Blur'>,
                                                                                         'ImageQuantize': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_post_processing.Quantize'>,
                                                                                         'ImageScaleToTotalPixels': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_post_processing.ImageScaleToTotalPixels'>,
                                                                                         'ImageSharpen': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_post_processing.Sharpen'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_rebatch.py': {   'RebatchLatents': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_rebatch.LatentRebatch'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_tomesd.py': {   'TomePatchModel': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_tomesd.TomePatchModel'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\comfy_extras\\nodes_upscale_model.py': {   'ImageUpscaleWithModel': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_upscale_model.ImageUpscaleWithModel'>,
                                                                                       'UpscaleModelLoader': <class 'C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_upscale_model.UpscaleModelLoader'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ASTERR': {   'ASTERR': <class 'ASTERR.nodes_asterr.ASTERRNode'>,
                                                                       'SaveASTERR': <class 'ASTERR.nodes_asterr.SaveASTERRScript'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyCache': {   'CacheCLIPTextEncode': <class 'ComfyCache.nodes_cache.CacheCLIPTextEncode'>,
                                                                           'CacheCheckpointLoader': <class 'ComfyCache.nodes_cache.CacheCheckpointLoader'>,
                                                                           'CacheCheckpointLoaderSimple': <class 'ComfyCache.nodes_cache.CacheCheckpointLoaderSimple'>,
                                                                           'CacheKSampler': <class 'ComfyCache.nodes_cache.CacheKSampler'>,
                                                                           'CacheKSamplerAdvanced': <class 'ComfyCache.nodes_cache.CacheKSamplerAdvanced'>,
                                                                           'CacheLoad': <class 'ComfyCache.nodes_cache.CacheLoad'>,
                                                                           'CacheSave': <class 'ComfyCache.nodes_cache.CacheSave'>,
                                                                           'CacheVAEDecode': <class 'ComfyCache.nodes_cache.CacheVAEDecode'>,
                                                                           'CacheVAEDecodeTiled': <class 'ComfyCache.nodes_cache.CacheVAEDecodeTiled'>,
                                                                           'CacheVAEEncode': <class 'ComfyCache.nodes_cache.CacheVAEEncode'>,
                                                                           'CacheVAEEncodeForInpaint': <class 'ComfyCache.nodes_cache.CacheVAEEncodeForInpaint'>,
                                                                           'CacheVAEEncodeTiled': <class 'ComfyCache.nodes_cache.CacheVAEEncodeTiled'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Disco-Diffusion': {   'DiscoDiffusion_DiscoDiffusion': <class 'ComfyUI-Disco-Diffusion.nodes.DiscoDiffusion'>,
                                                                                        'DiscoDiffusion_DiscoDiffusionExtraSettings': <class 'ComfyUI-Disco-Diffusion.nodes.DiscoDiffusionExtraSettings'>,
                                                                                        'DiscoDiffusion_GuidedDiffusionLoader': <class 'ComfyUI-Disco-Diffusion.nodes.GuidedDiffusionLoader'>,
                                                                                        'DiscoDiffusion_OpenAICLIPLoader': <class 'ComfyUI-Disco-Diffusion.nodes.OpenAICLIPLoader'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_ADV_CLIP_emb': {   'BNK_AddCLIPSDXLParams': <class 'ComfyUI_ADV_CLIP_emb.nodes.AddCLIPSDXLParams'>,
                                                                                     'BNK_AddCLIPSDXLRParams': <class 'ComfyUI_ADV_CLIP_emb.nodes.AddCLIPSDXLRParams'>,
                                                                                     'BNK_CLIPTextEncodeAdvanced': <class 'ComfyUI_ADV_CLIP_emb.nodes.AdvancedCLIPTextEncode'>,
                                                                                     'BNK_CLIPTextEncodeSDXLAdvanced': <class 'ComfyUI_ADV_CLIP_emb.nodes.AdvancedCLIPTextEncodeSDXL'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus': {   'IPAdapterApply': <class 'ComfyUI_IPAdapter_plus.IPAdapterPlus.IPAdapterApply'>,
                                                                                       'IPAdapterModelLoader': <class 'ComfyUI_IPAdapter_plus.IPAdapterPlus.IPAdapterModelLoader'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Noise': {   'BNK_GetSigma': <class 'ComfyUI_Noise.nodes.GetSigma'>,
                                                                              'BNK_InjectNoise': <class 'ComfyUI_Noise.nodes.InjectNoise'>,
                                                                              'BNK_NoisyLatentImage': <class 'ComfyUI_Noise.nodes.NoisyLatentImage'>,
                                                                              'BNK_SlerpLatent': <class 'ComfyUI_Noise.nodes.LatentSlerp'>,
                                                                              'BNK_Unsampler': <class 'ComfyUI_Noise.nodes.Unsampler'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Preset_Merger': {   'Preset_Model_Merge': <class 'ComfyUI_Preset_Merger.nodes.Preset_Model_Merge'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_SeeCoder': {   'ConcatConditioning': <class 'ComfyUI_SeeCoder.nodes.ConcatConditioning'>,
                                                                                 'SEECoderImageEncode': <class 'ComfyUI_SeeCoder.nodes.SEECoderImageEncode'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUi_NNLatentUpscale': {   'NNLatentUpscale': <class 'ComfyUi_NNLatentUpscale.nn_upscale.NNLatentUpscale'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\FreeU_Advanced': {   'FreeU (Advanced)': <class 'FreeU_Advanced.nodes.WAS_FreeU'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\LatentToRGB.py': {   'LatentToRGBTest': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\LatentToRGB.LatentToRGBTest'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\PowerNoiseSuite': {   'Blend Latents (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNBlendLatents'>,
                                                                                'Cross-Hatch Power Fractal (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNCrossHatchNode'>,
                                                                                'Cross-Hatch Power Fractal Settings (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNCrossHatchSettings'>,
                                                                                'Images as Latents (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNImageAsLatent'>,
                                                                                'Latent Adjustment (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNLatentAdjustment'>,
                                                                                'Latents to CPU (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNLatentToCPU'>,
                                                                                'Linear Cross-Hatch Power Fractal (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNLinearCrossHatchNode'>,
                                                                                'Perlin Power Fractal Latent (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNoiseNode'>,
                                                                                'Perlin Power Fractal Settings (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNoiseSettings'>,
                                                                                'Power KSampler Advanced (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNKSamplerAdvanced'>,
                                                                                'Power-Law Noise (PPF Noise)': <class 'PowerNoiseSuite.nodes.PPFNPowerLawNoise'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\SD-Latent-Upscaler': {   'LatentUpscaler': <class 'SD-Latent-Upscaler.comfy_latent_upscaler.LatentUpscaler'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\WAS_DebugThis.py': {   'DebugInput': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_DebugThis.WAS_DebugThis'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\WAS_Extras': {   'ConditioningBlend': <class 'WAS_Extras.ConditioningBlend.WAS_ConditioningBlend'>,
                                                                           'DebugInput': <class 'WAS_Extras.DebugThis.WAS_DebugThis'>,
                                                                           'VAEEncodeForInpaint (WAS)': <class 'WAS_Extras.VAEEncodeForInpaint.WAS_VAEEncodeForInpaint'>,
                                                                           'VividSharpen': <class 'WAS_Extras.VividSharpen.VividSharpen'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\advanced_model_merging.py': {   'ModelMergeBlockNumber': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\advanced_model_merging.ModelMergeBlockNumber'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\cliptextencode_a1111.py': {   'CLIPTextEncodeA1111': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cliptextencode_a1111.CLIPTextEncodeA1111'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfy-nodes': {   'CivitAI_CLIPTextEncode': <class 'comfy-nodes.civitai_cliptextencode.CivitAI_CLIPTextEncode'>,
                                                                            'CivitAI_Checkpoint_Loader': <class 'comfy-nodes.civitai_checkpoint_loader.CivitAI_Checkpoint_Loader'>,
                                                                            'CivitAI_Lora_Loader': <class 'comfy-nodes.civitai_lora_loader.CivitAI_LORA_Loader'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\reference_only.py': {   'ReferenceOnlySimple': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\reference_only.ReferenceOnlySimple'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\sampler_rescalecfg.py': {   'RescaleClassifierFreeGuidanceTest': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sampler_rescalecfg.RescaleClassifierFreeGuidance'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\sampler_tonemap.py': {   'ModelSamplerTonemapNoiseTest': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sampler_tonemap.ModelSamplerTonemapNoiseTest'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\sd-dynamic-thresholding': {   'DynamicThresholdingFull': <class 'sd-dynamic-thresholding.dynthres_comfyui.DynamicThresholdingComfyNode'>,
                                                                                        'DynamicThresholdingSimple': <class 'sd-dynamic-thresholding.dynthres_comfyui.DynamicThresholdingSimpleComfyNode'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\sdxl_model_merging.py': {   'ModelMergeSDXL': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_model_merging.ModelMergeSDXL'>,
                                                                                      'ModelMergeSDXLDetailedTransformers': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_model_merging.ModelMergeSDXLDetailedTransformers'>,
                                                                                      'ModelMergeSDXLTransformers': <class 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_model_merging.ModelMergeSDXLTransformers'>},
    'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\was-node-suite-comfyui': { OMITTED },
    'C:\\ComfyUI_windows_portable\\ComfyUI\\nodes.py': {   'CLIPLoader': <class 'nodes.CLIPLoader'>,
                                                           'CLIPSetLastLayer': <class 'nodes.CLIPSetLastLayer'>,
                                                           'CLIPTextEncode': <class 'nodes.CLIPTextEncode'>,
                                                           'CLIPVisionEncode': <class 'nodes.CLIPVisionEncode'>,
                                                           'CLIPVisionLoader': <class 'nodes.CLIPVisionLoader'>,
                                                           'CheckpointLoader': <class 'nodes.CheckpointLoader'>,
                                                           'CheckpointLoaderSimple': <class 'nodes.CheckpointLoaderSimple'>,
                                                           'ConditioningAverage': <class 'nodes.ConditioningAverage'>,
                                                           'ConditioningCombine': <class 'nodes.ConditioningCombine'>,
                                                           'ConditioningConcat': <class 'nodes.ConditioningConcat'>,
                                                           'ConditioningSetArea': <class 'nodes.ConditioningSetArea'>,
                                                           'ConditioningSetAreaPercentage': <class 'nodes.ConditioningSetAreaPercentage'>,
                                                           'ConditioningSetMask': <class 'nodes.ConditioningSetMask'>,
                                                           'ConditioningSetTimestepRange': <class 'nodes.ConditioningSetTimestepRange'>,
                                                           'ConditioningZeroOut': <class 'nodes.ConditioningZeroOut'>,
                                                           'ControlNetApply': <class 'nodes.ControlNetApply'>,
                                                           'ControlNetApplyAdvanced': <class 'nodes.ControlNetApplyAdvanced'>,
                                                           'ControlNetLoader': <class 'nodes.ControlNetLoader'>,
                                                           'DiffControlNetLoader': <class 'nodes.DiffControlNetLoader'>,
                                                           'DiffusersLoader': <class 'nodes.DiffusersLoader'>,
                                                           'DualCLIPLoader': <class 'nodes.DualCLIPLoader'>,
                                                           'EmptyImage': <class 'nodes.EmptyImage'>,
                                                           'EmptyLatentImage': <class 'nodes.EmptyLatentImage'>,
                                                           'GLIGENLoader': <class 'nodes.GLIGENLoader'>,
                                                           'GLIGENTextBoxApply': <class 'nodes.GLIGENTextBoxApply'>,
                                                           'ImageBatch': <class 'nodes.ImageBatch'>,
                                                           'ImageInvert': <class 'nodes.ImageInvert'>,
                                                           'ImagePadForOutpaint': <class 'nodes.ImagePadForOutpaint'>,
                                                           'ImageScale': <class 'nodes.ImageScale'>,
                                                           'ImageScaleBy': <class 'nodes.ImageScaleBy'>,
                                                           'KSampler': <class 'nodes.KSampler'>,
                                                           'KSamplerAdvanced': <class 'nodes.KSamplerAdvanced'>,
                                                           'LatentBlend': <class 'nodes.LatentBlend'>,
                                                           'LatentComposite': <class 'nodes.LatentComposite'>,
                                                           'LatentCrop': <class 'nodes.LatentCrop'>,
                                                           'LatentFlip': <class 'nodes.LatentFlip'>,
                                                           'LatentFromBatch': <class 'nodes.LatentFromBatch'>,
                                                           'LatentRotate': <class 'nodes.LatentRotate'>,
                                                           'LatentUpscale': <class 'nodes.LatentUpscale'>,
                                                           'LatentUpscaleBy': <class 'nodes.LatentUpscaleBy'>,
                                                           'LoadImage': <class 'nodes.LoadImage'>,
                                                           'LoadImageMask': <class 'nodes.LoadImageMask'>,
                                                           'LoadLatent': <class 'nodes.LoadLatent'>,
                                                           'LoraLoader': <class 'nodes.LoraLoader'>,
                                                           'PreviewImage': <class 'nodes.PreviewImage'>,
                                                           'RepeatLatentBatch': <class 'nodes.RepeatLatentBatch'>,
                                                           'SaveImage': <class 'nodes.SaveImage'>,
                                                           'SaveLatent': <class 'nodes.SaveLatent'>,
                                                           'SetLatentNoiseMask': <class 'nodes.SetLatentNoiseMask'>,
                                                           'StyleModelApply': <class 'nodes.StyleModelApply'>,
                                                           'StyleModelLoader': <class 'nodes.StyleModelLoader'>,
                                                           'UNETLoader': <class 'nodes.UNETLoader'>,
                                                           'VAEDecode': <class 'nodes.VAEDecode'>,
                                                           'VAEDecodeTiled': <class 'nodes.VAEDecodeTiled'>,
                                                           'VAEEncode': <class 'nodes.VAEEncode'>,
                                                           'VAEEncodeForInpaint': <class 'nodes.VAEEncodeForInpaint'>,
                                                           'VAEEncodeTiled': <class 'nodes.VAEEncodeTiled'>,
                                                           'VAELoader': <class 'nodes.VAELoader'>,
                                                           'unCLIPCheckpointLoader': <class 'nodes.unCLIPCheckpointLoader'>,
                                                           'unCLIPConditioning': <class 'nodes.unCLIPConditioning'>}}
```

### CODE REVIEW

**Comment by rvion** [comment]
how about only having unix-style paths ? they are universally compatible (windows, linux, macos)

**Comment by WASasquatch** [comment]
> how about only having unix-style paths ? they are universally compatible (windows, linux, macos)

It's the absolute path derived *from* the system.

**Comment by mcmonkey4eva** [comment]
If this is still needed, please rebuild it against modern ComfyUI

**Comment by WASasquatch** [comment]
It never had response from development at the time so I wouldn't waste my time rebuilding it for modern ComfyUI now. I've just been manually getting modules file from built-in in absence of file awareness in comfy.

**Pull request closed without merging**
