### PR TITLE
Add Internationalization (i18n) Support

### PR DESCRIPTION
**Pull request by xbol0**
This pull request adds internationalization (i18n) support to the project, making it accessible to a global audience. We've integrated i18next as an internal extension and extracted most user-visible strings into locale files.

Other contributors can refer to the web/i18n/*.js file format to add corresponding translation key-value pairs. Please ensure that English is included, as it's the fallback language defined in app.js.

This PR will impact project development and other extension development. Feel free to discuss with us.

### CODE REVIEW

**Comment by Yorha4D** [comment]
1 For translation, I recommend using plug-ins to manage. Previously, WEBUI tried to integrate multiple languages in the master main branch, but this would make it very difficult to merge the master branch every time, and increase the difficulty of updating and maintaining the master branch. So at that time, WEBUI removed the built-in multi-language after updating 3 versions, and used extension to manage it (after all, not everyone needs multi-language)
2 In addition, I did not find a way to switch languages, and some translations such as "Chong Chong Chong" have little relevance to the original button's "Queue Prompt", which seems to be "GO GO GO"?
image
3There are many places without translation
image
image
4In fact, the multilingual translation function has been completed, you can come here to maintain it together
https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION

**Comment by cx1132692358** [comment]
@xbol0 There are some issues with translation, such as K sampler ≠ sampler (Ksampler → K采样器), UPSCALE ≠ PIX, which should not be translated as adding pixels, Latent ≠ hidden space, etc
It is recommended not to excessively use mechanical translation to translate Chinese
This is the earliest ComfyUI Chinese video in China, with over tens of thousands of people using this translation. It is recommended to continue using this translation instead of creating new words
https://www.bilibili.com/video/BV1Fo4y187HC

**Comment by Yorha4D** [comment]
@xbol0 There are some issues with translation, such as K sampler ≠ sampler (Ksampler → K采样器), UPSCALE ≠ PIX, which should not be translated as adding pixels, Latent ≠ hidden space, etc
It is recommended not to excessively use mechanical translation to translate Chinese
This is the earliest ComfyUI Chinese video in China, with over tens of thousands of people using this translation. It is recommended to continue using this translation instead of creating new words
https://www.bilibili.com/video/BV1Fo4y187HC

**Comment by kelvinlong** [comment]
Thanks for your feedback. 

Agreed if the official opinion is to use extension to manage i18n support, we didn't find any opensource project on github providing i18n feature for ComfyUI, which is why we raised this PR. 

And it seems AIGODLIKE-COMFYUI-TRANSLATION project was submitted just around the couple days when the PR was reviewed. Anyway it's totally fine, we might consider using your extension for language support. 

We will close this PR soon.

> @xbol0 1 For translation, I recommend using plug-ins to manage. Previously, WEBUI tried to integrate multiple languages in the master main branch, but this would make it very difficult to merge the master branch every time, and increase the difficulty of updating and maintaining the master branch. So at that time, WEBUI removed the built-in multi-language after updating 3 versions, and used extension to manage it (after all, not everyone needs multi-language) 2 In addition, I did not find a way to switch languages, and some translations such as "Chong Chong Chong" have little relevance to the original button's "Queue Prompt", which seems to be "GO GO GO"? image 3There are many places without translation image image 4In fact, the multilingual translation function has been completed, you can come here to maintain it together https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION

**Comment by Yorha4D** [comment]
@kelvinlong 要来一起维护么~我喊负责人帮添加你

**Comment by kelvinlong** [comment]
> @kelvinlong 要来一起维护么~我喊负责人帮添加你

可以啊，请帮忙把@xbol0 加到comfyui的contributor list，正好有个进度提示的PR也需要提交下，很高兴一起来做贡献~~

**Comment by Yorha4D** [comment]
@xbol0 @kelvinlong 已添加

**Comment by kelvinlong** [comment]
> @xbol0 @kelvinlong 已添加
收到，多谢！但是我们希望加入ComfyUI的主项目，要提交的PR也是ComfyUI里面的功能哈

**Pull request closed without merging**
