### PR TITLE
feat: support loading custom node paths through environment variables

### PR DESCRIPTION
**Pull request by loonghao**
@comfyanonymous This MR added the `get_env_paths` and `get_custom_node_paths` functions to add detailed docstrings, in order to make the code more maintainable, reusable, and extensible. In particular, this MR adds support for loading custom node paths through environment variables, which improves the flexibility and usability of the code.

The modified functions now follow the Google Python Style Guide's conventions for clear and concise code comments and docstrings, covering the function description, parameters, return values and types, exceptions, and environment variable usage.

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Is there a reason for using env variables instead of command line arguments?

**Comment by loonghao** [comment]
@comfyanonymous 

Here is a polished version of your message:

There are several compelling reasons to opt for environment variables over command line arguments:

Flexibility: Environment variables can be set once and used across multiple sessions and commands, while command line arguments have to be specified every time a command is run. This makes environment variables more flexible and easier to manage, especially for complex workflows that involve multiple tools.

Customizability: Environmental variables can be customized for different users, systems, and environments, while command line arguments are limited to a specific command and may not cover all use cases.

Separation of concerns: Environment variables separate configuration from execution, making it easier to modify the configuration without affecting execution. Command line arguments blend configuration and execution, making the code more challenging to maintain and test.

Our team presently employs [Rez ](https://github.com/AcademySoftwareFoundation/rez)as our package and environment management tool. We generate a package for every custom node and manage the environment startup through [Rez](https://github.com/AcademySoftwareFoundation/rez).

below is a examples

```python
# c:\rez-pkg\comfyui_custom_node1\0.1.0\package.py

name = "comfyui_custom_node1"
version = "0.1.0"
requires = [
    "comfyu"
]
def commands():
    env.COMFYUI_CUSTOM_NODE_PATHS.append("{this.root}")
```

```python
# c:\rez-pkg\comfyui_custom_node2\1.1.1\package.py

name = "comfyui_custom_node2"
version = "1.1.1"
requires = [
    "comfyu",
    "numpy",
]
def commands():
    env.COMFYUI_CUSTOM_NODE_PATHS.append("{this.root}")
```

use command line launch the webui
```shell
rez-env comfyui_custom_node1-0 comfyui_custom_node2-1 comfyui -- comfyui
```

**Comment by missionfloyd** [comment]
All of that can be solved by putting them in a batch/shell script.

**Comment by ShawnDen-coder** [comment]
We really need this feature because most desktop software with similar node styles supports it. This is especially important in companies that deal with visual effects in the film and television industry. Developing this feature allows triggering nodes through environment variables, which is highly significant for process management.

**Comment by huchenlei** [comment]
Doable with yaml file now. Add an entry to `extra_model_paths.yaml`

**Pull request closed without merging**
