### PR TITLE
 Fix VAEEnocdeForInpaint to support denoise < 1.0 for inpainting model.

### PR DESCRIPTION
**Pull request by xucj98**

### CODE REVIEW

**Comment by xucj98** [comment]
To solve the issue [#1186](https://github.com/comfyanonymous/ComfyUI/issues/1186)

**Comment by jn-jairo** [comment]
It is awesome. In this example I tried to change the hair to blonde with different denoise values and it works as expected, the hair gets full blonde with denoise 1.0 and the denoise below 1.0 keeps more of the original image maintaining a good quality.

### Base Image
ComfyUI_temp_csyuf_00001_

### Denoise 0.5
ComfyUI_temp_uxjry_00003_

### Denoise 0.75
ComfyUI_temp_csyuf_00004_

### Denoise 1.0
ComfyUI_temp_csyuf_00002_

**Comment by ltdrdata** [comment]
This works like a charm!

**Comment by comfyanonymous** [comment]
I decided to implement this as a new node since I didn't want to change the behavior of the VAE Encode for inpaint in case some people depend on it: https://github.com/comfyanonymous/ComfyUI/commit/10f2609fdd2231faf40346df11372601385b6cbb

**Comment by PabloMontero** [comment]
Hello, totally newbie question.

I seen there are issues when applying Inpainting models when Inpainting.

Is this solved yet? Do I need to update Comfy?

And finally, is there any workflow or info to clarify this topic?

Thank you!

**Comment by jn-jairo** [comment]
> I seen there are issues when applying Inpainting models when Inpainting.
> 
> Is this solved yet? Do I need to update Comfy?

@PabloMontero yes, update the ComfyUI if you haven't yet, and use the node InpaintModelConditioning with an inpaint model.

**Comment by ghostsquad** [comment]
There are inpaint tutorials floating around. Might be worthwhile to update those. I've been confused as hell as to why things work/don't work in various situations. Thanks folks for your hard work on this!

**Comment by Gloynus** [comment]
> > I seen there are issues when applying Inpainting models when Inpainting.
> > Is this solved yet? Do I need to update Comfy?
> 
> @PabloMontero yes, update the ComfyUI if you haven't yet, and use the node InpaintModelConditioning with an inpaint model.

Please advise. Maybe some not-so-common way of updating ComfyUI is required (my ComfyUI version: 1869[66831e](2024-01-01)), but I can't find the "InpaintModelConditioning" node. How do I get the ability to use Inpainting models.

**Comment by PabloMontero** [comment]
I am not and advanced tech-user, but I found the node just updating from Comfy Manager extension > Update ComfyUI. Sorry if my answer is not relevant to what you are looking for.

**Comment by ltdrdata** [comment]
> Please advise. Maybe some not-so-common way of updating ComfyUI is required (my ComfyUI version: 1869[66831e](2024-01-01)), but I can't find the "InpaintModelConditioning" node. How do I get the ability to use Inpainting models.

Your ComfyUI is outdated version. Goto ComfyUI dir and execute `git pull`

**Comment by Gloynus** [comment]
> I am not and advanced tech-user, but I found the node just updating from Comfy Manager extension > Update ComfyUI. Sorry if my answer is not relevant to what you are looking for.

Oddly enough, this method didn't work yesterday. Today I did it again, ComfyUI was indeed updated and the node became available for work.
Thank you.

**Comment by ghostsquad** [comment]
Can InpaintModelConditioning be used even in the case of a non-inpainting model? Or does this need to be toggled on/off depending on the model?

**Pull request closed without merging**
