### PR TITLE
Add zoom controls to the web UI

### PR DESCRIPTION
**Pull request by JustinBStrong**
I've found zooming on my trackpad to be really finicky so I built controls to tell you the zoom level and provide more control over zoom. 

This PR adds zoom controls to the webs UI. The default workflow/view will initialize at 100% and update from the input, +/- buttons and via scroll wheel or touch zoom.

Screenshot, note the new controls below "Reset View"
Screenshot 2024-06-05 at 12 50 06 AM

### CODE REVIEW

**Comment by shawnington** [comment]
> I've found zooming on my trackpad to be really finicky so I built controls to tell you the zoom level and provide more control over zoom.
> 
> This PR adds zoom controls to the webs UI. The default workflow/view will initialize at 100% and update from the input, +/- buttons and via scroll wheel or touch zoom.
> 
> Screenshot, note the new controls below "Reset View" Screenshot 2024-06-05 at 12 50 06 AM

I need to review this, but I have frequent text box decoupling issues where the text fields decouple from nodes and are at a different zoom level, not sure if its related to this, but it is usually fixed by zooming into a text box and zooming out, which is weird, and I have no idea what would cause that behavior.

**Comment by ltdrdata** [comment]
For reference, the Ctrl+Shift+LMB Drag (↑↓) feature was added last time to support pen usage.
If the drag on the trackpad is LMB, it will apply in the same way.

**Comment by shawnington** [comment]
> For reference, the Ctrl+Shift+LMB Drag (↑↓) feature was added last time to support pen usage. If the drag on the trackpad is LMB, it will apply in the same way.

That does absolutely nothing on mac, just for future reference. Ctrl+shift+lmb or CMD+shift+lmb

Just tried with a wacom tablet also.

**Comment by ltdrdata** [comment]
> > For reference, the Ctrl+Shift+LMB Drag (↑↓) feature was added last time to support pen usage. If the drag on the trackpad is LMB, it will apply in the same way.
> 
> That does absolutely nothing on mac, just for future reference. Ctrl+shift+lmb or CMD+shift+lmb
> 
> Just tried with a wacom tablet also.
> 
> So the implementation is flawed.
> 
> CMD+SHIFT+ mouse scrolling does but lmb stops it.
> 
> So CMD+SHIFT+ moving the pen up and down on the tablet work, but not when holding the lmb equivalent on the pen.

not cmd it's ctrl

**Comment by shawnington** [comment]
> > > For reference, the Ctrl+Shift+LMB Drag (↑↓) feature was added last time to support pen usage. If the drag on the trackpad is LMB, it will apply in the same way.
> > 
> > 
> > That does absolutely nothing on mac, just for future reference. Ctrl+shift+lmb or CMD+shift+lmb
> > Just tried with a wacom tablet also.
> > So the implementation is flawed.
> > CMD+SHIFT+ mouse scrolling does but lmb stops it.
> > So CMD+SHIFT+ moving the pen up and down on the tablet work, but not when holding the lmb equivalent on the pen.
> 
> not cmd it's ctrl

ctrl is commonly translated to cmd for mac, ctrl does nothing at all, cmd does. But lmb stops the zoom action. cmd + shift + cursor up and down zoom for mac.

**Comment by JustinBStrong** [comment]
> > I've found zooming on my trackpad to be really finicky so I built controls to tell you the zoom level and provide more control over zoom.
> > This PR adds zoom controls to the webs UI. The default workflow/view will initialize at 100% and update from the input, +/- buttons and via scroll wheel or touch zoom.
> > Screenshot, note the new controls below "Reset View" Screenshot 2024-06-05 at 12 50 06 AM
> 
> I need to review this, but I have frequent text box decoupling issues where the text fields decouple from nodes and are at a different zoom level, not sure if its related to this, but it is usually fixed by zooming into a text box and zooming out, which is weird, and I have no idea what would cause that behavior.

My issue is that zooming in/out on a Mac trackpad has too much inertia/speed or something and ends up never zooming to where I want it to. I doubt it's related to this issue.

**Comment by shawnington** [comment]
> > > I've found zooming on my trackpad to be really finicky so I built controls to tell you the zoom level and provide more control over zoom.
> > > This PR adds zoom controls to the webs UI. The default workflow/view will initialize at 100% and update from the input, +/- buttons and via scroll wheel or touch zoom.
> > > Screenshot, note the new controls below "Reset View" Screenshot 2024-06-05 at 12 50 06 AM
> > 
> > 
> > I need to review this, but I have frequent text box decoupling issues where the text fields decouple from nodes and are at a different zoom level, not sure if its related to this, but it is usually fixed by zooming into a text box and zooming out, which is weird, and I have no idea what would cause that behavior.
> 
> My issue is that zooming in/out on a Mac trackpad has too much inertia/speed or something and ends up never zooming to where I want it to. I doubt it's related to this issue.

can confirm, its like 4x the normal zoom speed for mac, I never considered it an issue, but also, something I won't be able to un notice. 

Yes the zoom is like 4-6 times more sensitive than the native zoom in the browser. Thats actually probably what causes the text decoupling if there is ever a missed frame.

**Comment by mcmonkey4eva** [comment]
frontend is replaced by https://github.com/Comfy-Org/ComfyUI_frontend now

**Pull request closed without merging**
