### PR TITLE
Ability to switch between different graphs

### PR DESCRIPTION
**Pull request by JAlB-**
image

### CODE REVIEW

**Comment by ltdrdata** [comment]
Wow. Nice work!

**Comment by comfyanonymous** [comment]
What I meant is that I would like the workflows to be in a folder like: workflows/default_txt2img.json workflows/area_composition.json in the same format you get when you export them from the UI.

This is so I can easily modify them if I change things.

**Comment by JAlB-** [comment]
> What I meant is that I would like the workflows to be in a folder like: workflows/default_txt2img.json workflows/area_composition.json in the same format you get when you export them from the UI.
> 
> This is so I can easily modify them if I change things.

Can we implement this later? I just have some more ideas that I would like to implement to make using ComfyUI more convenient.

**Comment by comfyanonymous** [comment]
is it that difficult to implement? You can just put a list of filenames in the code and fetch them.

**Comment by JAlB-** [comment]
image
It's not that difficult, you can just download it and fix everything you want at once and save it. Thus, you can store an arbitrary number of presets without changing the code at all. To make such functionality with separate files, you will also have to write code in the server part that will give a list of files.

**Comment by comfyanonymous** [comment]
I only mean for the presets that are already there.

**Comment by comfyanonymous** [comment]
The: web/DefaultWorkflows.json should be multiple files like:  workflows/default_txt2img.json workflows/area_composition.json

**Comment by JAlB-** [comment]
> The: web/DefaultWorkflows.json should be multiple files like: workflows/default_txt2img.json workflows/area_composition.json

Do you think it makes sense to do this for presets that are loaded only once at the first launch? Then it's all not used anywhere.

**Comment by comfyanonymous** [comment]
yes because those presets will likely be modified a lot by me and others so I want it to be simple.

**Comment by JAlB-** [comment]
Then I will make an index file.json that will contain a list of files with presets. So will it be normal?

**Comment by comfyanonymous** [comment]
yes that's good.

**Comment by JAlB-** [comment]
To implement sequential downloading of several files so that nothing breaks quickly does not work, while I leave it like this. Either generate it on the server side or come up with a loading method that takes into account the asynchrony of requests. I'll probably do it tomorrow.

**Comment by WASasquatch** [comment]
This is awesome. Could use some Styling, like darker shade than graph BG but not black against white which is terrible for eyes and not advised for sale themes. Buttons could use BGs.

**Comment by JAlB-** [comment]
I did the loading of default graphs from several files.

**Comment by FraYoshi** [comment]
I like this addition!
Would be great if it could be toggleable, maybe on the side menu that is already there!

**Comment by JAlB-** [comment]
I plan to move the side menu to the top menu. It's just not such an important task to do it now. Now I want to make an additional interface to interact with the nodes and a graphical editor.

**Comment by KaruroChori** [comment]
Oh no, you got there first :smile:  . I was also working on GUI to add libraries, history and multiple graphs. The main issue is that litegraph.js has few bugs :/.
image

**Comment by omar92** [comment]
that will be great

**Comment by omar92** [comment]
any updates on this ??

**Comment by comfyanonymous** [comment]
>any updates on this ??

If you want it merged faster you should test it and let us know if you find any bugs or if everything works fine.

**Comment by omar92** [comment]
> > any updates on this ??
> 
> If you want it merged faster you should test it and let us know if you find any bugs or if everything works fine.

ok sure , thanks for the hard work

**Comment by omar92** [comment]
im kinda new in that stuff , shall i clone the whole repo again , or there are a way to only see the changes

**Comment by omar92** [comment]
oh sorry had to clear the browser cache

**Comment by ltdrdata** [comment]
I'm going to die waiting for it.

**Comment by Hawox** [comment]
Been driving this, must have feature or something akin to it. Brings this closer to the usability / friendliness of A1111 by being able to rapidly switch through workflows without manually managing save files.

**Comment by JAlB-** [comment]
Unfortunately, I can't devote as much time to the project as I would like. If there is a desire to help, then I will not refuse to help.

**Comment by M1kep** [comment]
@JAlB- what features are missing in this currently? Are there any bugs your already aware of?

**Comment by WASasquatch** [comment]
This is really old and likely not even compatible with a merge to test without manually fixing things.

**Pull request closed without merging**
