### PR TITLE
Add polyexponential and vp schedulers.

### PR DESCRIPTION
**Pull request by simonlui**
Polyexponential seems alright with all the samplers tested but VP seems to have some issues with the samplers that don't converge like dpmpp_3m_sde or uni_pc schedulers where there seems to be a bunch of noise added right at the end to the image or corruption to some brown noisy image for no discernible reason. Putting it to draft so this can be tested out and evaluated whether any of new schedulers should get in or not.

Edit: Did some additional testing overall, and PR should be good enough to exit draft status besides the issues I mentioned with VP.

### CODE REVIEW

**Comment by fractal-fumbler** [comment]
after https://github.com/comfyanonymous/ComfyUI/commit/1d6dd8318463e896abf9f99cf5381438ee64d302 patch isn't applied.

i wonder SDE-VP is some kind of merge of SDE and VP schedulers?

**Comment by simonlui** [comment]
> after [1d6dd83](https://github.com/comfyanonymous/ComfyUI/commit/1d6dd8318463e896abf9f99cf5381438ee64d302) patch isn't applied.
> 
> i wonder SDE-VP is some kind of merge of SDE and VP schedulers?

This pull request was made redundant via 213976f8c3ea3f45f0c692dd8aac2fd9fea433e3 where these samplers are now custom nodes in the testing folder. And with that, this PR will be closed.

**Comment by fractal-fumbler** [comment]
thanks, VP is still missing in custom nodes :) hope it will be added soon

**Comment by simonlui** [comment]
VP had issues with certain samplers as I stated so I wouldn't hold out for it if it can't be made to work.

**Comment by fractal-fumbler** [comment]
well, time to test :D
https://github.com/comfyanonymous/ComfyUI/commit/2ef459b1d4d627929c84d11e5e0cbe3ded9c9f48

**Pull request closed without merging**
