### PR TITLE
Add holding directory for IPAdapters

### PR DESCRIPTION
**Pull request by fofr**
The most popular IPAdapter custom node https://github.com/cubiq/ComfyUI_IPAdapter_plus puts these models into the `models/ipadapter` directory.

This PR adds that holding directory as a default.

cc @cubiq

### CODE REVIEW

**Comment by fofr** [comment]
@cubiq Added in [46ffc92](https://github.com/comfyanonymous/ComfyUI/pull/3299/commits/46ffc92acdae5db2b3e6e70a0b83d771e0d8f605)

**Comment by kaalibro** [comment]
But the extension [already supports](https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/0d0a7b3693baf8903fe2028ff218b557d619a93d/IPAdapterPlus.py#L33C1-L38C105) external directories. I added the `ipadapter` in `extra_model_paths.yaml` and it works. Unless I've misunderstood the intent of this PR.

Screenshot 2024-04-20 115014

**Comment by fofr** [comment]
The intent of this PR is just to bring IPAdapters inline with other model types.

**Comment by mcmonkey4eva** [comment]
This should probably be handled in the IP-Adapter extension?
Or if for whatever reason it's unable to be handled from there, a generic API for it on the comfy side so extension can handle it as-needed.

**Pull request closed without merging**
