### PR TITLE
feat: LoRA Block Weights

### PR DESCRIPTION
**Pull request by ltdrdata**
LoraLoaderBlockWeights node added.

Simply, apply weight to lora/locon blocks.

### CODE REVIEW

**Comment by aetherwu** [comment]
Vote for Merge PR.

**Comment by ltdrdata** [comment]
need to rework completely.

**Comment by ltdrdata** [comment]
> It seems that this node cannot be used（not found it）.
> 
> How can I use this node,please
> 
> thanks

Currently, this feature is completely incompatible. It only works with the older version of ComfyUI.

**Comment by OwenTruong** [comment]
> > It seems that this node cannot be used（not found it）.
> > How can I use this node,please
> > thanks
> 
> Currently, this feature is completely incompatible. It only works with the older version of ComfyUI.

Any roadmap or plans on updating it for the newer version?

**Comment by ltdrdata** [comment]
> > > It seems that this node cannot be used（not found it）.
> > > How can I use this node,please
> > > thanks
> > 
> > 
> > Currently, this feature is completely incompatible. It only works with the older version of ComfyUI.
> 
> Any roadmap or plans on updating it for the newer version?

I have already created it in the form of a custom node.

https://github.com/ltdrdata/ComfyUI-Inspire-Pack
https://www.youtube.com/watch?v=X9v0xQrInn8

**Pull request closed without merging**
