### PR TITLE
Add bool widget

### PR DESCRIPTION
**Pull request by missionfloyd**
Functions like a checkbox.
Returns `true` or `false`
Defaults: `("BOOL", {"default": False, "on": "true", "off": "false"}`

https://user-images.githubusercontent.com/4073789/231663147-d344e0b4-50a8-45ef-92df-acdedbf1521d.mp4

I've also updated every input that has exactly two choices.

### CODE REVIEW

**Comment by comfyanonymous** [comment]
Can you make it automatically use the BOOL widget in the frontend when there are only 2 choices in a combo? I think it would be better this way because it would automatically apply to custom nodes as well and wouldn't need any changes in the backend.

**Comment by missionfloyd** [comment]
I'm not sure how that would work. If you make a combo, you'll expect it to return a string, but this returns a bool.

**Comment by ltdrdata** [comment]
Can you change bool widget to switch style instead of toggle?



If combo has just 2 item then represent as a labeled switch otherwise show original combo.

I think we need such that.

**Comment by ltdrdata** [comment]
oh... forget switch thing... the widget shows text already.

Just if you implement item count sensitive widget. That will be nice.

2 items => bool widget.
n items => combo widget.

**Comment by WASasquatch** [comment]
> I'm not sure how that would work. If you make a combo, you'd expect it to return a string, but this returns a bool.

This should be assumed as a front end UX fix, where we don't worry about the output. That way we don't change how custom nodes work.

**Pull request closed without merging**
