### PR TITLE
 solve the number input equation (allow simple equations on number fields  like 512 * 2 = 1024) 

### PR DESCRIPTION
**Pull request by omar92**
if the number in put is something like (2+2)*3

it will write 12

### CODE REVIEW

**Comment by omar92** [comment]
i made a pull request on litegraph.js for that change too ,

**Comment by mligaintart** [comment]
I think js.eval might be a bit risky?  It sounds like a security nightmare if someone posts a workflow with malicious javascript that could communicate and use the backend server as an attack vector.

**Comment by omar92** [comment]
i can remove characters before eval , but thanks for letting me know

**Comment by omar92** [comment]
my actual concern is that i changed the library file , i need to find a solution to do that withought changing lib file

**Comment by atlasan** [comment]
you could override the
LGraphCanvas.prototype.processNodeWidgets instead of changing the lib itself

**Comment by omar92** [comment]
sadly on litegraph.js the first thing that happens to number input is parsing it which will lead to Nan 
i made pull request there (at litegraph)to organize that part I hope they will accept the change , then after that I do this feature here in a clean way

**Comment by omar92** [comment]
this change now is on the original  litegraph  as the owner of litegraph already accepted that merge request and comfui is updated , so thanks all

**Pull request closed without merging**
